/**
 * cfgfix.test.ts — the configurability FIX round (Y1–Y12): the three
 * adversarial reviewers' probes (cfgrev-a/b/c), ported as named regressions.
 * Modules are imported as namespaces so a test that needs what the frozen
 * pre-fix oracle lacks fails alone; the fail-first run against
 * synthesis-config/ is ../cfgfix-prefix.txt (regenerated by
 * ../cfgfix-prefix.sh). Run: tsx cfgfix.test.ts
 */
import { exercise, fn, kg, num, pct, reps, rir, roundTo, sets, some, ty, type Q, type Term, type Ty } from './algebra'
import { canonicalJson } from './canonical'
import * as CK from './checker'
import * as CD from './checkdefs'
import * as DS from './describe'
import * as DD from './describe-defs'
import * as DR from './describe-run'
import type { TypeError, Value } from './engine'
import * as EV from './evaluate'
import * as IS from './issue'
import * as JU from './judge'
import * as OP from './options'
import * as P from './programs'
import * as PO from './ports'
import * as ST from './step'
import { ev, program, single } from './structure'
import * as TI from './time'
import * as TK from './testkit'
import * as XF from './xform'

const { t, done } = TK.suite('cfgfix')
const assert: (ok: unknown, msg: string) => asserts ok = TK.assert
const { eq, near, reg, D0 } = TK
const codes = (es: readonly TypeError[]) => es.map((e) => `${e.code}@${e.path.join('.')}`)
const progErrors = (def: Parameters<typeof CD.checkProgram>[0]) => codes(CD.checkProgram(def, reg).flatMap((r) => r.errors))
const SQUAT = exercise('wger:111')
const lit = (v: number, unit: string): Term => ({ k: 'lit', lit: { k: 'q', v, unit } }) as Term

// ── shared judged-session scaffolding (the reviewers' probe shape) ──────────

const stepT = (id: string, count: object, repsB: object, role = 'working'): object => ({ k: 'step', id, count, target: { k: 'set', role, target: { reps: repsB }, rest: null, tempo: null, cluster: null } })
const sessionT = (steps: object[]): Term => ({ k: 'session', exercise: { k: 'lit', lit: { k: 'ref', kind: 'exercise', id: 'push-up' } }, steps, intensifier: null }) as unknown as Term
const exact = (v: number) => ({ b: 'exact', v: lit(v, 'rep') })
const nOf = (n: number) => ({ k: 'n', n: lit(n, 'set') })
const srcOf = (tm: Term, perf: Record<string, (number | null)[]>, extra: Partial<JU.EventSource> = {}): JU.EventSource => {
  const v = EV.evaluate(tm, EV.ctxOf(reg)).value
  if (v.v !== 'session') throw new Error('no session')
  return {
    reg,
    slots: [{ slot: 'x', exercise: { id: 'push-up', label: 'Push-Up', logging: 'bodyweight_reps' }, steps: v.s.steps, intensifier: null, trace: { node: tm, value: v, kids: [] } }],
    performed: { x: Object.fromEntries(Object.entries(perf).map(([k, rs]) => [k, rs.map((r) => (r === null ? { values: {}, stages: null } : { values: { reps: r }, stages: null }))])) },
    facts: [],
    groupScores: {},
    week: 0,
    primary: () => undefined,
    ...extra,
  }
}
const vd = (src: JU.EventSource, rule?: Parameters<typeof JU.verdictOf>[3], edge: 'floor' | 'top' = 'floor') => JU.verdictOf(src, 'working', edge, rule)

// ── Y1: totalReps counts all logged judged sets, matching its prose ─────────

t('', 'Y1 (fail-first, B-P2): totalReps over a 3–5 count range of exact-5: [3,3,3,3,3] totals 15 of 15, a hit (the pre-fix oracle credited the floor’s 3 sets only)', () => {
  const tr = sessionT([stepT('w', { k: 'range', min: lit(3, 'set'), max: lit(5, 'set') }, exact(5))])
  eq(vd(srcOf(tr, { w: [3, 3, 3, 3, 3] }), 'totalReps'), 'hit', '15 across all five logged sets clears the 3-set floor of 15')
})

t('', 'Y1 (fail-first, B-P2b corrected to the GZCLP shape): a make-up set beyond the expected count pays into the pool: 5× exact-3 logged [3,3,3,2,2,3] totals 16 of 15, a hit', () => {
  const t5 = sessionT([stepT('w', nOf(5), exact(3))])
  eq(vd(srcOf(t5, { w: [3, 3, 3, 2, 2, 3] }), 'totalReps'), 'hit', 'the sixth set rescues the two short ones')
  eq(vd(srcOf(t5, { w: [3, 3, 3, 2, 2] }), 'totalReps'), 'missed', 'without it, 13 of 15 with every expected set logged is a miss')
})

t('', 'Y1 (A-p3): an expected set logged WITHOUT reps blocks a miss but not a hit: [10, ∅, 6] on 3× exact-5 already totals 16', () => {
  const t3 = sessionT([stepT('w', nOf(3), exact(5))])
  eq(vd(srcOf(t3, { w: [10, null, 6] }), 'totalReps'), 'hit', 'credit is decidable early')
  eq(vd(srcOf(t3, { w: [5, null, 4] }), 'totalReps'), 'unknown', 'and a short total with a silent set stays open')
})

t('', 'Y1 (C, pinned as documented): the pool is the SLOT’s: two judged steps pool their floors and credits; a warm-up step under `working` pays nothing in', () => {
  const t2 = sessionT([stepT('a', nOf(3), exact(5)), stepT('b', nOf(2), exact(8))])
  eq(vd(srcOf(t2, { a: [5, 5, 5], b: [16, 0] }), 'totalReps'), 'hit', '31 of 31 across both steps')
  const wu = sessionT([stepT('wu', nOf(2), exact(5), 'warmup'), stepT('w', nOf(3), exact(5))])
  eq(vd(srcOf(wu, { wu: [10, 10], w: [5, 5, 4] }), 'totalReps'), 'missed', 'warm-up reps never rescue the working total')
  const t0 = sessionT([stepT('w', nOf(0), exact(5))])
  eq(vd(srcOf(t0, {}), 'totalReps'), 'unknown', 'a zero-set planned line judges nothing (B-P3, the C9 stance)')
})

// ── Y2: atLeastSets cannot be unsatisfiable; silence is never a miss ────────

t('', 'Y2 (fail-first, B-P1): atLeastSets 5 on a 3-set slot: nothing logged is UNKNOWN (the pre-fix oracle called silence a miss), and all three hit is a HIT (the cap is the issued sets)', () => {
  const t3 = sessionT([stepT('w', nOf(3), exact(5))])
  eq(vd(srcOf(t3, { w: [] }), { atLeastSets: 5 }), 'unknown', 'silence is never a miss')
  eq(vd(srcOf(t3, { w: [5, 5, 5] }), { atLeastSets: 5 }), 'hit', 'an all-hit session hits')
  eq(vd(srcOf(t3, { w: [5, 4, 4] }), { atLeastSets: 5 }), 'missed', 'two logged misses still miss (cap 3, hits 1)')
})

t('', 'Y2 (A-p3): a deload that scales 3 sets to 1 under atLeastSets 3: the one issued set hit is a HIT, nothing logged stays unknown', () => {
  const deload: Term = { k: 'xform', op: 'scaleSets', s: sessionT([stepT('w', nOf(3), exact(5))]), arg: lit(0.5, 'x'), metric: null } as unknown as Term
  eq(vd(srcOf(deload, { w: [5] }), { atLeastSets: 3 }), 'hit', 'the plan issued one set; the athlete hit it')
  eq(vd(srcOf(deload, { w: [] }), { atLeastSets: 3 }), 'unknown', 'and silence stays unknown')
})

t('', 'Y2 (static, C-p1): an atLeastSets no session shape of the bound plan can hold is refused at the slot meta (literalDomain), through literal binding arguments', () => {
  const mk = (n: number) =>
    program({
      id: 'prog/cfgfix-als',
      version: 1,
      says: 'x',
      params: {},
      calendar: { weeks: ['train'], repeat: 'cycle' },
      grids: { load: kg(2.5) },
      muscles: ['quads'],
      slots: () => ({ squat: P.linearGated.bind({ lift: SQUAT, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { quads: 1 }, success: { atLeastSets: n } }) }),
      days: { A: [single('squat')] },
      rotation: { k: 'weekly', days: ['A'] },
    }).def
  assert(progErrors(mk(99)).includes('literalDomain@slots.squat.meta.success'), '99 sets can never come from a 3-set plan')
  eq(progErrors(mk(3)), [], 'the satisfiable declaration checks clean')
})

// ── Y3: the five redefined definitions are republished as @2 ────────────────

t('', 'Y3: the registry holds BOTH versions of each touched definition: @1 is the pre-round body (no declared success, the literal constants), @2 carries the round’s changes, and the corpus binds @2', () => {
  for (const id of ['lib/gzclp-t1', 'lib/double-progression', 'lib/531-jokers', 'lib/hr-tempo', 'lib/pain-gated-loading']) {
    assert(reg.schemes.get(`${id}@1`), `${id}@1 is published`)
    assert(reg.schemes.get(`${id}@2`), `${id}@2 is published`)
  }
  const v1 = reg.schemes.get('lib/gzclp-t1@1')!
  assert(!JSON.stringify(v1.on).includes('"success"'), '@1 judges allSets, as it always did')
  assert(!v1.says.includes('counting total reps'), '@1 keeps its pre-round template')
  const v2 = reg.schemes.get('lib/gzclp-t1@2')!
  assert(JSON.stringify(v2.on).includes('"totalReps"'), '@2 declares the method’s rule')
  eq(reg.schemes.get('lib/double-progression@1')!.defaults, undefined, '@1 has no defaults: lo/hi were literals')
  assert(reg.schemes.get('lib/double-progression@2')!.defaults?.['lo'], '@2 carries the promoted defaults')
  eq(P.gzclpT1Program.def.slots['squat']!.scheme.version, 2, 'the corpus program rebinds to @2')
  // Z1 corrects the old pin here: the rebinding is no longer an in-place
  // hash move under a constant program version — the rebound program is a
  // NEW version (@2), and @1 keeps its published body, bound to the @1
  // scheme, byte-for-byte (progs-v1.ts; cmp-progs-v1.ts is the independent
  // byte-check against the recorded kits).
  eq(P.gzclpT1Program.def.ref.version, 2, 'the rebound program is a new version')
  eq(reg.programs.get('prog/gzclp-t1@1')!.slots['squat']!.scheme.version, 1, '@1 still binds the @1 scheme')
  assert(PO.hashOf(reg.programs.get('prog/gzclp-t1@2')!) !== PO.hashOf(reg.programs.get('prog/gzclp-t1@1')!), 'the two versions hash apart')
})

// ── Y4: one form per meaning, enforced for every option ─────────────────────

t('', 'Y4 (fail-first, A/B/C): every explicit-default spelling is refused where the ties default already was: one meaning, one form', () => {
  const base = P.linear3x5.def
  assert(progErrors({ ...base, e1rm: { formula: 'epley' } }).some((c) => c.startsWith('literalDomain@e1rm')), 'e1rm {formula: epley} alone')
  assert(progErrors({ ...base, ties: 'down' as never }).some((c) => c.startsWith('literalDomain@ties')), "ties 'down'")
  assert(progErrors({ ...base, adherenceWeeks: 'fromAnchor' as never }).some((c) => c.startsWith('literalDomain@adherenceWeeks')), "adherenceWeeks 'fromAnchor'")
  assert(progErrors({ ...base, volumeWeights: {} }).some((c) => c.startsWith('literalDomain@volumeWeights')), 'volumeWeights {}')
  assert(progErrors({ ...base, volumeWeights: { stage: 0.5, cluster: 1 } }).some((c) => c.startsWith('literalDomain@volumeWeights')), 'volumeWeights at its defaults')
  assert(progErrors({ ...base, staleness: {} }).some((c) => c.startsWith('literalDomain@staleness')), 'staleness {}')
  assert(progErrors({ ...base, staleness: { e1rm: reg.vocab.facts['e1rm']!.maxAgeDays! } }).some((c) => c.startsWith('literalDomain@staleness')), 'staleness at the registry value (B-P7)')
  assert(progErrors({ ...P.upperHypertrophy.def, stripIntensifierOn: ['deload', 'taper', 'test'] }).some((c) => c.startsWith('literalDomain@stripIntensifierOn')), 'the default strip set spelled out')
})

t('', 'Y4 set-valued options have ONE spelling: duplicates and non-calendar order are refused, and the embedding canonicalizes to the same form (C-p1)', () => {
  const mk = (strip?: string[]) =>
    program({
      id: 'prog/cfgfix-strip',
      version: 1,
      says: 'x',
      params: {},
      calendar: { weeks: ['train', 'deload', 'taper', 'test'], repeat: 'cycle' },
      grids: { load: kg(2.5) },
      muscles: ['quads'],
      slots: () => ({ squat: P.linearGated.bind({ lift: SQUAT, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { quads: 1 } }) }),
      days: { A: [single('squat')] },
      rotation: { k: 'weekly', days: ['A'] },
      ...(strip ? { stripIntensifierOn: strip as never } : {}),
    }).def
  assert(progErrors({ ...mk(), stripIntensifierOn: ['deload', 'deload'] as never }).some((c) => c.startsWith('literalDomain@stripIntensifierOn')), 'a duplicate role')
  assert(progErrors({ ...mk(), stripIntensifierOn: ['taper', 'deload'] as never }).some((c) => c.startsWith('literalDomain@stripIntensifierOn')), 'an order off the calendar’s')
  eq(progErrors({ ...mk(), stripIntensifierOn: ['deload', 'taper'] as never }), [], 'the canonical spelling (calendar order) checks clean')
  // Z2: the one-form comparison is IN EFFECT — the default set intersected
  // with the calendar's roles spells omission, whatever the calendar.
  assert(progErrors({ ...mk(), stripIntensifierOn: ['deload', 'taper', 'test'] as never }).some((c) => c.startsWith('literalDomain@stripIntensifierOn')), 'the default set in effect is a second form')
  eq(PO.hashOf(mk(['taper', 'deload'])), PO.hashOf(mk(['deload', 'taper'])), 'the embedding canonicalizes both spellings to one IR')
  eq(mk(['deload', 'deload', 'taper'])!.stripIntensifierOn, ['deload', 'taper'], 'and drops duplicates')
  eq(mk(['test', 'deload', 'taper'])!.stripIntensifierOn, undefined, 'and drops the default set in effect (Z2)')
  const s = reg.schemes.get('lib/double-progression@2')!
  assert(codes(CD.checkScheme({ ...s, ref: { ...s.ref, id: 'lib/dp-e' as never }, defaults: {} }, reg)).some((c) => c.startsWith('literalDomain@defaults')), 'defaults {} spells no defaults: refused')
})

// ── Y5: ties (and display) thread through every context builder ─────────────

t('', 'Y5 (fail-first, A-p4): `round nearest` INSIDE a published fn follows the program’s tie direction: 101.25 on 2.5 rounds to 102.5 via the fn under ties-up, exactly as inline', () => {
  const plate = fn<{ x: Q<'mass'> }, Q<'mass'>>({ id: 'user/plate', version: 1, params: { x: ty.q('mass') }, result: ty.q('mass'), says: '{x} to a plate', examples: [{ args: { x: kg(100) }, gives: kg(100) }], body: (p) => roundTo(p.x, kg(2.5)) })
  const extraFns = new Map([[CK.keyOf(plate.def.ref), plate.def]])
  const viaFn = plate({ x: kg(101.25) }).term
  const n = (v: Value) => (v.v === 'q' ? v.n : NaN)
  eq(n(EV.evaluate(viaFn, EV.ctxOf(reg, { extraFns, ties: 'up' })).value), 102.5, 'the fn call sees the declaration')
  eq(n(EV.evaluate(viaFn, EV.ctxOf(reg, { extraFns })).value), 100, 'and defaults stay down')
})

t('', 'Y5 setsDue evaluates an until/while condition under the STAMPED seams: a round-nearest tie inside the condition follows the stamped direction', () => {
  const cond: Term = { k: 'cmp', op: '==', a: { k: 'round', mode: 'nearest', a: lit(101.25, 'kg'), step: lit(2.5, 'kg') }, b: lit(102.5, 'kg') } as unknown as Term
  const target = { role: 'working', metrics: { reps: { k: 'fixed', v: { b: 'exact', v: 5 } } }, restSec: null, tempo: null, cluster: null }
  const st = { id: 'w', key: 'w', count: { k: 'while', max: 3, planned: 3 }, sets: [target, target, target], block: null, live: { cond, frame: { vars: {}, reads: {} } } }
  const view = { slot: 'x', exercise: { id: 'push-up', label: 'Push-Up', logging: 'bodyweight_reps' }, steps: [st], intensifier: null, trace: { node: cond, value: { v: 'bool', b: true }, kids: [] } }
  eq(IS.setsDue({ reg }, view as never, st as never, { w: [{ values: { reps: 5 }, stages: null }] }, { ties: 'up', display: {} }), 2, 'under the ties-up stamp the while-condition holds: another set is due')
  eq(IS.setsDue({ reg }, view as never, st as never, { w: [{ values: { reps: 5 }, stages: null }] }), 1, 'under the default stamp it does not')
})

// ── Y6: e1rm skips out-of-domain sets instead of vetoing the read ───────────

const e1rmSrc = (vals: { reps: number; load: number }[], decl?: NonNullable<JU.EventSource['e1rm']>): JU.EventSource => {
  const run = TK.start(P.linear3x5.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  return { reg, slots: x.issued.slots.filter((s) => s.slot === 'squat'), performed: { squat: { work: vals.map((v) => ({ values: v, stages: null })) } }, facts: [], groupScores: {}, week: 0, primary: () => 'quads', ...(decl ? { e1rm: decl } : {}) }
}
const e1rmOf = (vals: { reps: number; load: number }[], decl?: NonNullable<JU.EventSource['e1rm']>) => JU.eventPort(e1rmSrc(vals, decl))({ q: 'e1rm', step: 'work' } as EV.EventRead)

t('', 'Y6 (fail-first, B-P4): one out-of-domain set no longer silences the read: [5@100, 12@60] under maxReps 10 estimates from the qualifying heavy set', () => {
  near((e1rmOf([{ reps: 5, load: 100 }, { reps: 12, load: 60 }], { formula: 'epley', maxReps: 10 }) as { n: number }).n, 100 * (1 + 5 / 30), 'the burnout is skipped, not a veto')
  near((e1rmOf([{ reps: 5, load: 100 }, { reps: 38, load: 20 }], { formula: 'brzycki' }) as { n: number }).n, (100 * 36) / (37 - 5), 'the formula’s own edge skips the same way (B-P4b)')
})

t('', 'Y6 absent only when NO set qualifies, naming the best offender; the cause carries the program’s cap when maxReps bound it', () => {
  eq(e1rmOf([{ reps: 40, load: 50 }, { reps: 38, load: 50 }], { formula: 'brzycki' }), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'brzycki', reps: 38 } }, 'the closest-to-qualifying set is the offender')
  eq(e1rmOf([{ reps: 14, load: 60 }], { formula: 'epley', maxReps: 12 }), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'epley', reps: 14, cap: 12 } }, 'the cap names the PROGRAM’s rule')
  eq(DR.absenceText({ k: 'outsideFormulaDomain', formula: 'epley', reps: 14, cap: 12 }, reg), "no set qualified: 14 effective reps is over the program's declared cap of 12", 'and the prose says which rule bit')
  assert(progErrors({ ...P.linear3x5.def, e1rm: { formula: 'brzycki', maxReps: 40 } }).includes('literalDomain@e1rm.maxReps'), 'a maxReps beyond the formula’s domain could never bind: refused')
})

// ── Y7: the declared formula governs the program’s math ─────────────────────

t('', 'Y7 (fail-first): lib/load-for computes the DECLARED inverse: under a Brzycki program, seeding and the e1RM read round-trip on one formula', () => {
  const E = 120
  const app: Term = { k: 'app', def: { id: 'lib/load-for', version: 1 }, args: { e1rm: lit(E, 'kg'), reps: lit(5, 'rep'), rir: lit(0, 'rir') } } as unknown as Term
  const n = (v: Value) => (v.v === 'q' ? v.n : NaN)
  near(n(EV.evaluate(app, EV.ctxOf(reg, { e1rm: { formula: 'brzycki' } })).value), (E * (37 - 5)) / 36, 'the Brzycki inverse')
  near(n(EV.evaluate(app, EV.ctxOf(reg)).value), E / (1 + 5 / 30), 'no declaration keeps the published Epley body')
  const w = (E * (37 - 5)) / 36
  near((e1rmOf([{ reps: 5, load: w }], { formula: 'brzycki' }) as { n: number }).n, E, 'the round trip closes (X6 for every formula)')
})

t('', 'Y7 end to end: a program declaring brzycki seeds its working weight from the Brzycki inverse at activation; a declared estimator nothing consumes is refused', () => {
  const E = (TK.E1RM['wger:111'] as { n: number }).n
  const brz = TK.start({ ...P.linear3x5.def, e1rm: { formula: 'brzycki' } }, {}, TK.corpusFacts())
  const load = TK.stateOf(brz, 'squat', 'load')
  assert(load.v === 'q', 'seeded')
  near(load.n, (E * (37 - 6)) / 36, 'loadFor(e1rm, 5 reps, 1 RIR): r = 6 through the declared inverse')
  assert(progErrors({ ...P.fiveThreeOneBBB.def, e1rm: { formula: 'brzycki' } }).some((c) => c.startsWith('literalDomain@e1rm')), '5/3/1-BBB never reads ev.e1rm nor calls load-for: dead config (the C8 posture)')
})

// ── Y8: a read can override back to allSets ─────────────────────────────────

t('', 'Y8 (fail-first, C-p5): the read wins in BOTH directions: a slot-declared totalReps is overridden back to per-set by an explicit allSets read', () => {
  const t3 = sessionT([stepT('w', nOf(3), exact(5))])
  const slotRule: Partial<JU.EventSource> = { success: { x: 'totalReps' } }
  eq(vd(srcOf(t3, { w: [9, 7, 0] }, slotRule)), 'hit', 'the slot rule pools: 16 of 15')
  eq(vd(srcOf(t3, { w: [9, 7, 0] }, slotRule), 'allSets'), 'missed', 'the explicit allSets read judges each set at its own bar')
  eq(ev.verdict(undefined, 'floor', 'allSets').term, { k: 'event', q: { q: 'verdict', steps: 'working', bound: 'floor', success: 'allSets' } }, 'the embedding keeps the override (a field widening, not a former)')
  const out: TypeError[] = []
  CK.top(ev.verdict(undefined, 'floor', 'allSets').term, { ...CK.baseScope(reg, 'handler', {}, { id: 'demo/cfgfix', seq: reg.seq.size }), steps: { earlier: [], all: 'any' as const, own: null } }, [], null, out)
  eq(codes(out), [], 'and the IR accepts it at the read')
  eq(DS.describe(ev.verdict(undefined, 'floor', 'allSets').term, DS.cxOf(reg, { slotSuccess: 'totalReps' })), 'How the working sets went (every set at its own bar).', 'the override is spoken, never mute')
})

t('', 'Y8 a slot-level success no read can ever consume is flagged like dead staleness', () => {
  const dead = program({
    id: 'prog/cfgfix-dead',
    version: 1,
    says: 'x',
    params: {},
    calendar: { weeks: ['train'], repeat: 'cycle' },
    grids: { load: kg(2.5) },
    muscles: ['quads'],
    slots: () => ({ main: P.w531Jokers.bind({ lift: SQUAT, tm: some(kg(100)) }, { muscles: { quads: 1 }, success: 'totalReps' }) }),
    days: { A: [single('main')] },
    rotation: { k: 'weekly', days: ['A'] },
  }).def
  assert(progErrors(dead).includes('literalDomain@slots.main.meta.success'), '531-jokers has no handlers, so no verdict read ever consumes the rule')
})

// ── Y9: instance overrides are durable, typed, and spoken ───────────────────

t('', 'Y9 (fail-first): activation records the overrides on the instance, so a runtime rebuilt from the HEAD alone has the same spec and window geometry', () => {
  const rt = PO.runtime(reg, P.linear3x5.def, { id: 'ov', anchor: D0, activatedOn: D0, overrides: { lapseAfterDays: 5, adherenceWeeks: { calendarAligned: { weekStart: 'Monday' } } } })
  const head = ST.activate(rt, {}, TK.factsOf({}))
  eq(head.instance.overrides, { lapseAfterDays: 5, adherenceWeeks: { calendarAligned: { weekStart: 'Monday' } } }, 'the record is on the head')
  const rebuilt = PO.runtime(reg, P.linear3x5.def, head.instance)
  eq(canonicalJson(rebuilt.spec), canonicalJson(rt.spec), 'replay without the activation call sees the same spec, so expectation keys cannot collide across alignments')
  const base = ST.activate(PO.runtime(reg, P.linear3x5.def, { id: 'ov', anchor: D0, activatedOn: D0 }), {}, TK.factsOf({}))
  eq(base.instance.overrides, undefined, 'no overrides, no field: a default head is byte-identical')
})

t('', 'Y9 bad overrides are typed refusals with their cause, and an override spelling the program’s own value is a second form, refused', () => {
  const r1 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { adherenceWeeks: { calendarAligned: { weekStart: 'Monday' as never } } })
  assert(!('code' in r1), 'a real override is accepted')
  const r2 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { adherenceWeeks: { calendarAligned: { weekStart: 'Mondy' as never } } })
  assert('code' in r2 && r2.code === 'badOverride' && (r2 as { option: string }).option === 'adherenceWeeks.calendarAligned.weekStart', 'a misspelt weekday is a typed refusal, never a throw')
  const r3 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { lapseAfterDays: P.linear3x5.def.lapseAfterDays })
  assert('code' in r3 && r3.code === 'badOverride', 'the program’s own value is not an override')
  const rt = PO.runtime(reg, P.linear3x5.def, { id: 'ov5', anchor: D0, activatedOn: D0, overrides: { lapseAfterDays: 5 } })
  eq(DD.lapseText(rt.spec), "If you don't train for 5 days, attendance stops counting until your next session.", 'the instance surface states the ACTIVE value')
  assert(DD.describeProgram(P.linear3x5.def, DS.cxOf(reg)).some((l) => l.includes("If you don't train for 21 days")), 'the program description keeps the declared one')
})

// ── Y10: refusal holes closed ───────────────────────────────────────────────

t('', 'Y10 (fail-first): malformed option JSON is a typed refusal at every position, never a raw TypeError', () => {
  const base = P.linear3x5.def
  const errsOf = (over: object) => progErrors({ ...base, ...over } as never)
  assert(errsOf({ stripIntensifierOn: 'deload' }).some((c) => c.startsWith('unknownName@stripIntensifierOn')), 'a non-array strip list')
  assert(errsOf({ e1rm: null }).some((c) => c.startsWith('unknownName@e1rm')), 'e1rm null')
  assert(errsOf({ e1rm: {} }).some((c) => c.startsWith('unknownName@e1rm.formula')), 'e1rm {} (A-p2)')
  assert(errsOf({ volumeWeights: '0.5' }).some((c) => c.startsWith('unknownName@volumeWeights')), 'a string where a record belongs')
  assert(errsOf({ volumeWeights: { stage: '0.5' } }).some((c) => c.startsWith('literalDomain@volumeWeights')), 'a string weight')
  assert(errsOf({ staleness: null }).some((c) => c.startsWith('unknownName@staleness')), 'staleness null')
  assert(errsOf({ staleness: { e1rm: 1.5 } }).some((c) => c.startsWith('literalDomain@staleness')), 'fractional days')
  assert(errsOf({ adherenceWeeks: 'calendarAligned' }).some((c) => c.startsWith('unknownName@adherenceWeeks')), 'the alignment without its weekday')
  assert(errsOf({ adherenceWeeks: { calendarAligned: {} } }).some((c) => c.startsWith('unknownName@adherenceWeeks')), 'an empty alignment record')
  assert(errsOf({ ties: null }).some((c) => c.startsWith('unknownName@ties')), 'ties null')
  const badMeta = { ...base, slots: { ...base.slots, squat: { ...base.slots['squat']!, meta: { muscles: { quads: 1 }, success: 'allSets' } } } }
  assert(progErrors(badMeta as never).some((c) => c.startsWith('unknownName@slots.squat.meta.success')), "the slot meta refuses 'allSets': omitted IS allSets there")
})

// ── Y11: prose repairs ──────────────────────────────────────────────────────

t('', 'Y11 (fail-first): a range over PROMOTED defaults reads as the literal it replaced: optLoaded’s bench line says “8–12 reps” again, byte-identical to the pre-round prose', () => {
  const lines = DD.describeSlot(reg.schemes.get('lib/double-progression@2')!, { lift: 'Barbell Bench Press', sets: '4 sets', inc: '2.5 kg', start: 'nothing' }, DS.cxOf(reg))
  assert(lines.some((l) => l.includes('8–12 reps')), `the compaction is back on the plan line: ${lines.find((l) => l.includes('Plan'))}`)
  assert(!lines.join('\n').includes('8 reps to 12 reps'), 'and the spelled-out form is gone')
  const dc = DD.describeSlot(reg.schemes.get('lib/rest-pause-dc@1')!, { lift: 'Flat DB Press', sets: '2 sets', lo: '8 reps', hi: '12 reps', total: '20 reps', inc: '2 kg' }, DS.cxOf(reg))
  assert(dc.some((l) => l.includes('8 reps to 12 reps')), 'a NON-defaulted param range keeps its spelled-out form, as the pre-round prose had it')
})

t('', 'Y11 the ties-up parenthetical renders once per grid sentence, and the C10 append names params by their display labels', () => {
  const def = { ...P.linear3x5.def, grids: { ...P.linear3x5.def.grids, distance: lit(0.5, 'km') }, ties: 'up' as const }
  const gridLine = DD.describeProgram(def as never, DS.cxOf(reg)).find((l) => l.includes('grid'))!
  eq(gridLine.split('rounds up').length - 1, 1, `one parenthetical over two grids: ${gridLine}`)
  const jokers = DD.describeProgram(
    program({
      id: 'prog/cfgfix-jk',
      version: 1,
      says: 'x',
      params: {},
      calendar: { weeks: ['train'], repeat: 'cycle' },
      grids: { load: kg(2.5) },
      muscles: ['quads'],
      slots: () => ({ main: P.w531Jokers.bind({ lift: SQUAT, tm: some(kg(100)), jokerStep: pct(110) }, { muscles: { quads: 1 } }) }),
      days: { A: [single('main')] },
      rotation: { k: 'weekly', days: ['A'] },
    }).def,
    DS.cxOf(reg),
  )
  assert(jokers.some((l) => l.includes('(with Joker step = 110%)')), `the label, never the identifier: ${jokers.find((l) => l.includes('with'))}`)
})

// ── Y12: allowZero scales the whole count range ─────────────────────────────

t('', 'Y12 (fail-first, A-13): under allowZero a count range scales as ONE line: it drops to nothing when the scaled min hits zero, so a 0-min range over live sets cannot exist', () => {
  const target = { role: 'working', metrics: { reps: { k: 'fixed', v: { b: 'exact', v: 5 } } }, restSec: null, tempo: null, cluster: null }
  const s = { exercise: { v: 'ref', kind: 'exercise', id: 'push-up' }, steps: [{ id: 'w', key: 'w', count: { k: 'range', min: 1, max: 4 }, sets: [target, target, target, target], block: null, live: null }], intensifier: null }
  const scaled = XF.applyXform('scaleSets', s as never, { v: 'q', n: 0.25, dim: {}, unit: 'pct' }, null, null, null, true)
  eq(scaled.steps[0]!.count, { k: 'range', min: 0, max: 0 }, 'the line is gone whole: min and max together')
  eq(scaled.steps[0]!.sets.length, 0, 'and no targets are issued')
  const kept = XF.applyXform('scaleSets', s as never, { v: 'q', n: 0.5, dim: {}, unit: 'pct' }, null, null, null, true)
  eq(kept.steps[0]!.count, { k: 'range', min: 0, max: 0 }, '1 × 50% rounds to zero: still the whole line')
  const surviving = { ...s, steps: [{ ...s.steps[0]!, count: { k: 'range', min: 2, max: 4 } }] }
  eq(XF.applyXform('scaleSets', surviving as never, { v: 'q', n: 0.5, dim: {}, unit: 'pct' }, null, null, null, true).steps[0]!.count, { k: 'range', min: 1, max: 2 }, 'a surviving range keeps the one-set floor and stays a real range')
  const dflt = XF.applyXform('scaleSets', s as never, { v: 'q', n: 0.25, dim: {}, unit: 'pct' }, null, null, null)
  eq(dflt.steps[0]!.count, { k: 'range', min: 1, max: 1 }, 'without the option the F12 floor holds unchanged')
})

// ── the options table is the one source (Y4 structural) ─────────────────────

t('', 'Y4 structural: the one options table serves the judge, the sink, the counters and the describers: its defaults are the engine’s, spelled once', () => {
  eq(OP.DEFAULT_E1RM_FORMULA, 'epley', 'the judge reads the table')
  eq([...OP.STRIP_DEFAULT], ['deload', 'taper', 'test'], 'L10 reads the table')
  eq(OP.VOLUME_DEFAULTS, { stage: 0.5, cluster: 1 }, 'the volume counter reads the table')
  eq(OP.E1RM_FORMULA_NAMES, ['epley', 'brzycki', 'lombardi', 'mayhew'], 'one formula list for the checker, the schema and the judge')
  for (const f of OP.E1RM_FORMULA_NAMES) near(OP.E1RM_FORMULAS[f].inverse(OP.E1RM_FORMULAS[f].of(100, 5), 5), 100, `${f}: of and inverse are each other's round trip`)
})

done()
