/**
 * config.test.ts — the configurability round (owner-ratified): every declared
 * option C1–C11 exercised at a NON-default value through issue, judge, step
 * and prose, with a checker negative beside it. Modules are imported as
 * namespaces, as in semfix.test.ts, so a test that needs what the pre-round
 * oracle lacks fails alone; the fail-first run against synthesis-patfix is
 * ../config-prefix.txt (regenerated by ../config-prefix.sh).
 * Run: tsx config.test.ts
 */
import { exercise, kg, num, pct, reps, sets, some, type Term, type Ty } from './algebra'
import * as CK from './checker'
import * as CD from './checkdefs'
import * as DS from './describe'
import * as DD from './describe-defs'
import * as DR from './describe-run'
import type { TypeError, Value } from './engine'
import * as EV from './evaluate'
import * as IS from './issue'
import * as JU from './judge'
import * as P from './programs'
import * as ER from './endurance-rehab'
import * as PO from './ports'
import * as ST from './step'
import { linearGated, doubleProg, w531Jokers } from './programs'
import { program, scheme, single } from './structure'
import * as TI from './time'
import * as TK from './testkit'
import * as UN from './units'
import * as XF from './xform'

const { t, done } = TK.suite('config')
const assert: (ok: unknown, msg: string) => asserts ok = TK.assert
const { eq, near, reg, D0 } = TK
const codes = (es: readonly TypeError[]) => es.map((e) => `${e.code}@${e.path.join('.')}`)
const progErrors = (def: Parameters<typeof CD.checkProgram>[0]) => codes(CD.checkProgram(def, reg).flatMap((r) => r.errors))
const SQUAT = exercise('wger:111')
const noneMass: Value = { v: 'none', cause: { k: 'declaredNone' } }

// ── C1: the verdict success rule ────────────────────────────────────────────

const gzStart = () => TK.start(P.gzclpT1Program.def, { squatStart: noneMass }, TK.corpusFacts())

/** Log the squat's 5×3+ with the given per-set reps, loads as prescribed. */
const logReps = (issued: Parameters<typeof TK.logWith>[0], repCounts: (number | null)[]) => {
  let i = 0
  return TK.logWith(issued, (_s, _st, _i, tg) => {
    const p = EV.asPrescribedSet(tg)
    const r = repCounts[i++]
    return r === null ? null : { ...p, values: { ...p.values, reps: r } }
  })
}

t('', 'C1 GZCLP (fail-first): 3,3,3,2,5 totals 16 of 15, so T1 is a HIT under the method’s totalReps rule: the load rises and the stage holds (the pre-round oracle demoted the stage)', () => {
  const run = gzStart()
  const x = TK.issue(run, D0)
  const before = TK.stateOf(x.run, 'squat', 'load')
  assert(before.v === 'q', 'the squat load is known from e1rm')
  const r = TK.close(x.run, x.issued, logReps(x.issued, [3, 3, 3, 2, 5]), D0)
  eq(TK.stateOf(r.run, 'squat', 'stage'), { v: 'enum', name: 'gzT1', tag: '5x3' }, 'the stage holds')
  const after = TK.stateOf(r.run, 'squat', 'load')
  assert(after.v === 'q' && Math.abs(after.n - (before.n + 5)) < 1e-9, `the working weight rises by 5 kg: ${JSON.stringify(after)}`)
})

t('', 'C1 totalReps is decidable early in both directions: a reps-only partial log that already clears the total is a hit, a full log short of it is a miss, a short partial log is unknown', () => {
  // A reps-only line, so the total is the only bar (another metric's
  // unlogged bar would still hold the verdict at unknown, as stated).
  const sessionT: Term = { k: 'session', exercise: { k: 'lit', lit: { k: 'ref', kind: 'exercise', id: 'push-up' } }, steps: [{ k: 'step', id: 'w' as never, count: { k: 'n', n: { k: 'lit', lit: { k: 'q', v: 3, unit: 'set' } } }, target: { k: 'set', role: 'working', target: { reps: { b: 'exact', v: { k: 'lit', lit: { k: 'q', v: 5, unit: 'rep' } } } }, rest: null, tempo: null, cluster: null } }], intensifier: null }
  const v = EV.evaluate(sessionT, EV.ctxOf(reg)).value
  assert(v.v === 'session', 'the session evaluates')
  const src = (repCounts: number[]): JU.EventSource => ({ reg, slots: [{ slot: 'x', exercise: { id: 'push-up', label: 'Push-Up', logging: 'bodyweight_reps' }, steps: v.v === 'session' ? v.s.steps : [], intensifier: null, trace: { node: sessionT, value: v, kids: [] } }], performed: { x: { w: repCounts.map((r) => ({ values: { reps: r }, stages: null })) } }, facts: [], groupScores: {}, week: 0, primary: () => undefined })
  eq(JU.verdictOf(src([9, 7]), 'working', 'floor', 'totalReps'), 'hit', '16 logged with a set unlogged already clears 15')
  eq(JU.verdictOf(src([5, 5, 4]), 'working', 'floor', 'totalReps'), 'missed', 'every set logged, 14 of 15')
  eq(JU.verdictOf(src([5, 5]), 'working', 'floor', 'totalReps'), 'unknown', '10 so far decides nothing')
  eq(JU.verdictOf(src([5, 5, 4]), 'working', 'floor'), 'missed', 'allSets still misses on the short set')
  const gz = TK.issue(gzStart(), D0)
  const gzSrc = (counts: (number | null)[]): JU.EventSource => ({ reg, slots: gz.issued.slots, performed: logReps(gz.issued, counts), facts: [], groupScores: {}, week: 0, primary: () => 'quads' })
  eq(JU.verdictOf(gzSrc([8, 8, null, null, null]), 'working', 'floor', 'totalReps'), 'unknown', 'with a load bar on every set, an unlogged set still holds the verdict open')
})

/** A 3×5 slot whose SLOT META declares atLeastSets 2 (C1's per-slot form). */
const cfgTwoOfThree = program({
  id: 'prog/cfg-two-of-three',
  version: 1,
  says: 'config-round worked program: success when 2 of 3 sets hit',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: { load: kg(2.5) },
  muscles: ['quads'],
  slots: () => ({ squat: linearGated.bind({ lift: SQUAT, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { quads: 1 }, success: { atLeastSets: 2 } }) }),
  days: { A: [single('squat')] },
  rotation: { k: 'weekly', days: ['A'] },
})

t('', 'C1 atLeastSets, declared per slot: 2 hits and a miss progress the load; 1 hit, 1 miss and 1 unlogged set is unknown; two misses are a miss', () => {
  const run = TK.start(cfgTwoOfThree.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  const before = TK.stateOf(x.run, 'squat', 'load')
  assert(before.v === 'q', 'known at activation')
  const r = TK.close(x.run, x.issued, logReps(x.issued, [5, 5, 4]), D0)
  const after = TK.stateOf(r.run, 'squat', 'load')
  assert(after.v === 'q' && Math.abs(after.n - (before.n + 2.5)) < 1e-9, `2 of 3 hit: the slot hits: ${JSON.stringify(after)}`)
  const y = TK.issue(r.run, TK.day('2026-10-07'))
  const src = (counts: (number | null)[]): JU.EventSource => ({ reg, slots: y.issued.slots, performed: logReps(y.issued, counts), facts: [], groupScores: {}, week: 0, primary: () => 'quads', success: { squat: { atLeastSets: 2 } } })
  eq(JU.verdictOf(src([5, 4, null]), 'working', 'floor'), 'unknown', 'one hit, one miss, one silent set could still decide it')
  eq(JU.verdictOf(src([4, 4, null]), 'working', 'floor'), 'missed', 'two misses: at most one set can still hit')
  eq(JU.verdictOf(src([5, 4, 5]), 'working', 'floor'), 'hit', 'the read-level default comes from the slot map')
})

const aggT = (opts: Record<string, unknown>): Term => ({ k: 'event', q: { q: 'verdict', steps: 'working', bound: 'floor', ...opts } } as Term)
const scopeAt = (position: 'handler' | 'aggregate' = 'handler') => ({ ...CK.baseScope(reg, position, {}, { id: 'demo/config', seq: reg.seq.size }), steps: { earlier: [], all: 'any' as const, own: null } })
const check = (term: Term, want: Ty | null = null, position: 'handler' | 'aggregate' = 'handler') => {
  const out: TypeError[] = []
  CK.top(term, scopeAt(position), [], want, out)
  return codes(out)
}

t('', 'C1 negatives: an unknown success rule and an atLeastSets below 1 are refused at the option, in the read and in the slot meta', () => {
  eq(check(aggT({ success: 'mostReps' })), ['unknownName@q.success'], 'no such rule on the read')
  eq(check(aggT({ success: { atLeastSets: 0 } })), ['literalDomain@q.success'], 'zero sets could never hit')
  eq(check(aggT({ success: 'totalReps' })), [], 'the declared rule checks clean')
  const bad = { ...cfgTwoOfThree.def, slots: { squat: { ...cfgTwoOfThree.def.slots['squat']!, meta: { muscles: { quads: 1 }, success: { atLeastSets: 0 } } } } }
  assert(progErrors(bad).includes('literalDomain@slots.squat.meta.success'), 'the slot meta is checked too')
})

t('', 'C1 prose: the verdict read and its match arms state the declared rule; the slot line states the per-slot one', () => {
  const cx = DS.cxOf(reg)
  eq(DS.describe(aggT({}), cx), 'How the working sets went.', 'default, unchanged')
  eq(DS.describe(aggT({ success: 'totalReps' }), cx), 'How the working sets went (counting total reps across all sets).', 'the read states totalReps')
  eq(DS.describe(aggT({ success: { atLeastSets: 2 } }), cx), 'How the working sets went (at least 2 sets must fully hit).', 'the read states atLeastSets')
  const gz = reg.schemes.get('lib/gzclp-t1@1')!
  const handler = DS.describe(gz.on.session!, DS.cxOf(reg, { lib: true, nouns: { stage: 'stage', load: 'working weight' } }))
  assert(handler.includes('totalled their target reps'), `GZCLP’s arms state the total-reps rule: ${handler}`)
  const lines = DD.describeProgram(cfgTwoOfThree.def, DS.cxOf(reg))
  assert(lines.some((l) => l.includes('Success: at least 2 sets must fully hit.')), `the slot line states the rule: ${lines.find((l) => l.startsWith('  squat'))}`)
})

// ── C2: the e1RM estimator ──────────────────────────────────────────────────

const e1rmSrcOf = (decl?: { formula: 'epley' | 'brzycki' | 'lombardi' | 'mayhew'; maxReps?: number }) => {
  const run = TK.start(P.linear3x5.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  const logged = TK.logWith(x.issued, (_s, _st, _i, tg) => ({ ...EV.asPrescribedSet(tg), values: { reps: 5, load: 100 } }))
  const src: JU.EventSource = { reg, slots: x.issued.slots.filter((s) => s.slot === 'squat'), performed: logged, facts: [], groupScores: {}, week: 0, primary: () => 'quads', ...(decl ? { e1rm: decl } : {}) }
  return (q: EV.EventRead) => JU.eventPort(src)(q)
}
const nOf = (v: Value): number => (v.v === 'q' ? v.n : NaN)

t('', 'C2 (fail-first): the program’s declared formula drives ev.e1rm, a read-level formula wins, and every formula shares the X6 effective-reps rule', () => {
  const port = e1rmSrcOf({ formula: 'brzycki' })
  near(nOf(port({ q: 'e1rm', step: 'work' } as EV.EventRead)), (100 * 36) / (37 - 5), 'Brzycki at 100 kg × 5')
  near(nOf(port({ q: 'e1rm', step: 'work', formula: 'epley' } as EV.EventRead)), 100 * (1 + 5 / 30), 'the read-level override wins')
  near(nOf(e1rmSrcOf()({ q: 'e1rm', step: 'work' } as EV.EventRead)), 100 * (1 + 5 / 30), 'no declaration is still Epley')
  near(nOf(e1rmSrcOf({ formula: 'lombardi' })({ q: 'e1rm', step: 'work' } as EV.EventRead)), 100 * Math.pow(5, 0.1), 'Lombardi')
  near(nOf(e1rmSrcOf({ formula: 'mayhew' })({ q: 'e1rm', step: 'work' } as EV.EventRead)), (100 * 100) / (52.2 + 41.9 * Math.exp(-0.055 * 5)), 'Mayhew')
})

t('', 'C2 out-of-domain reps are a typed absence (outsideFormulaDomain), for the formula’s own edge and for a declared maxReps', () => {
  const run = TK.start(P.linear3x5.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  const logged = TK.logWith(x.issued, (_s, _st, _i, tg) => ({ ...EV.asPrescribedSet(tg), values: { reps: 40, load: 60 } }))
  const srcOf = (decl: NonNullable<JU.EventSource['e1rm']>): JU.EventSource => ({ reg, slots: x.issued.slots.filter((s) => s.slot === 'squat'), performed: logged, facts: [], groupScores: {}, week: 0, primary: () => 'quads', e1rm: decl })
  eq(JU.eventPort(srcOf({ formula: 'brzycki' }))({ q: 'e1rm', step: 'work' } as EV.EventRead), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'brzycki', reps: 40 } }, 'Brzycki stops at 36 effective reps')
  eq(JU.eventPort(srcOf({ formula: 'epley', maxReps: 12 }))({ q: 'e1rm', step: 'work' } as EV.EventRead), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'epley', reps: 40 } }, 'a declared maxReps caps every formula')
  eq(DR.absenceText({ k: 'outsideFormulaDomain', formula: 'brzycki', reps: 40 }, reg), '40 effective reps is more than the Brzycki estimate covers', 'the absence says why')
})

t('', 'C2 negatives and prose: unknown formulas are refused at the read and the declaration, maxReps 0 is refused, and the program line names the formula', () => {
  eq(check({ k: 'event', q: { q: 'e1rm', step: 'work', formula: 'brzyycki' } } as never), ['unknownName@q.formula'], 'the read')
  assert(progErrors({ ...P.linear3x5.def, e1rm: { formula: 'bryzcki' as never } }).includes('unknownName@e1rm.formula'), 'the declaration')
  assert(progErrors({ ...P.linear3x5.def, e1rm: { formula: 'brzycki', maxReps: 0 } }).includes('literalDomain@e1rm.maxReps'), 'maxReps 0')
  const cx = DS.cxOf(reg)
  eq(DS.describe({ k: 'event', q: { q: 'e1rm', step: 'work', formula: 'brzycki' } } as Term, cx), 'The max estimated from “work” (Brzycki).', 'the read names the formula')
  const lines = DD.describeProgram({ ...P.linear3x5.def, e1rm: { formula: 'brzycki', maxReps: 10 } }, cx)
  assert(lines.some((l) => l === '  Estimated one-rep maxes use the Brzycki formula, from sets of at most 10 effective reps.'), `the program states it: ${lines[3]}`)
})

// ── C3: adherence week alignment ────────────────────────────────────────────

t('', 'C3 (fail-first): calendarAligned weeks open on the declared weekday, not on the anchor; the first partial week before activation opens nothing', () => {
  // D0+2 is Wednesday 7 October; aligned weeks run Monday to Sunday.
  const wed = TK.day('2026-10-07')
  const rt = PO.runtimeOf(reg, P.linear3x5.def, { id: 'aligned', anchor: wed, activatedOn: wed, overrides: { adherenceWeeks: { calendarAligned: { weekStart: 'Monday' } } } })
  eq(rt.spec.adherenceWeeks, { calendarAligned: { weekStart: 'Monday' } }, 'the override reaches the spec')
  const head = ST.activate(rt, {}, TK.factsOf({}))
  eq(head.calendar.expectations, [], 'no window opens mid-week: the lead-in days are uncounted')
  let cal = head.calendar
  for (let n = TI.dayNum(wed); n < TI.dayNum(TK.day('2026-10-20')); n++) cal = TI.stepCalendar(rt.spec, cal, { k: 'dayClosed', causeKey: `day:aligned:${TI.dayOf(n)}`, day: TI.dayOf(n) })
  const x = cal.expectations[0]!
  eq(x.window, { from: TK.day('2026-10-12'), through: TK.day('2026-10-18') }, 'the first window is the next calendar week')
  const a = cal.adherence.find((r) => r.expectation === x.key)!
  eq(TI.derivedAdherence(cal, a.key).missed, 3, 'closed unmet by its Sunday')
  const prose = DD.adherenceText(cal, a, rt.spec)
  eq(prose, 'Calendar week (Monday 12 October to Sunday 18 October): 0 of 3 workouts (3 missed).', 'attendance prose says calendar week, never a window number')
})

t('', 'C3 the program-level declaration, its prose and its negative', () => {
  const def = { ...P.linear3x5.def, adherenceWeeks: { calendarAligned: { weekStart: 'Monday' as const } } }
  const spec = TI.calendarSpecOf(def, [], 'x', D0, D0)
  eq(spec.adherenceWeeks, { calendarAligned: { weekStart: 'Monday' } }, 'declared on the program')
  const lines = DD.describeProgram(def, DS.cxOf(reg))
  assert(lines.some((l) => l.includes('in each calendar week (Monday to Sunday)')), `the frequency prose is aligned: ${lines.find((l) => l.startsWith('  Attendance'))}`)
  assert(DD.describeProgram(P.linear3x5.def, DS.cxOf(reg)).some((l) => l.includes('in each 7-day window (from your start day)')), 'the default prose is unchanged')
  assert(progErrors({ ...def, adherenceWeeks: { calendarAligned: { weekStart: 'Mondy' as never } } }).includes('unknownName@adherenceWeeks.calendarAligned.weekStart'), 'a misspelt weekday is refused')
})

// ── C4: technique-stage and cluster volume weights ──────────────────────────

const weeklySets = (def: typeof P.upperHypertrophy.def, muscle: string): number => {
  const run = TK.start(def, {}, TK.corpusFacts())
  const v = PO.aggPort(run.rt, run.ledger.head, { facts: TK.factsOf({}), today: D0, earlierToday: 0, reads: PO.newReads() })({ q: 'weekly', metric: 'sets', by: { k: 'muscle', id: muscle } })
  return nOf(v)
}

t('', 'C4 (fail-first): volumeWeights drive the weekly sets read: a full-weight stage raises chest, a half-weight cluster set halves back', () => {
  near(weeklySets(P.upperHypertrophy.def, 'chest'), 6, 'default: (2 sets + 2 stages × 0.5) × 2 sessions')
  near(weeklySets(P.upperHypertrophy.def, 'back'), 8, 'default: 4 cluster sets × 1 × 2 sessions')
  near(weeklySets({ ...P.upperHypertrophy.def, volumeWeights: { stage: 1 } }, 'chest'), 8, 'a stage declared a whole set')
  near(weeklySets({ ...P.upperHypertrophy.def, volumeWeights: { cluster: 0.5 } }, 'back'), 4, 'a cluster set declared half')
})

t('', 'C4 negatives and prose: weights outside (0, 1] are refused; the program line states a declared weight', () => {
  assert(progErrors({ ...P.upperHypertrophy.def, volumeWeights: { stage: 0 } }).includes('literalDomain@volumeWeights.stage'), 'zero')
  assert(progErrors({ ...P.upperHypertrophy.def, volumeWeights: { cluster: 1.5 } }).includes('literalDomain@volumeWeights.cluster'), 'above one')
  const lines = DD.describeProgram({ ...P.upperHypertrophy.def, volumeWeights: { stage: 1 } }, DS.cxOf(reg))
  assert(lines.some((l) => l === '  Volume counting: an intensifier stage counts as 100% of a set.'), 'stated')
})

// ── C5: the intensifier-strip roles ─────────────────────────────────────────

t('', 'C5 (fail-first): stripIntensifierOn [] keeps the rest-pause through the deload; the default drops it (L10’s list is now the program’s)', () => {
  // The deload ROLE TRANSFORM (deloadStd) also strips, so both variants
  // drop it to isolate L10: only the sink's own strip is under test.
  const noRolePolicy = P.upperHypertrophy.def.policies.filter((x) => x.origin !== 'role')
  const toDeload = (def: typeof P.upperHypertrophy.def) => {
    const run = TK.train(TK.start(def, {}, TK.corpusFacts()), 6, D0).run
    eq(run.ledger.head.progress.week, 3, 'the deload week')
    return TK.issue(run, TK.day('2026-10-19')).issued
  }
  const kept = toDeload({ ...P.upperHypertrophy.def, policies: noRolePolicy, stripIntensifierOn: [] })
  assert(kept.slots.find((s) => s.slot === 'press')!.intensifier !== null, 'declared []: the intensifier survives the deload')
  eq(toDeload({ ...P.upperHypertrophy.def, policies: noRolePolicy }).slots.find((s) => s.slot === 'press')!.intensifier, null, 'default: L10 drops it in the deload')
})

t('', 'C5 negatives and prose: a role outside the calendar is refused (the X4 posture), an unknown role is unknownName, and the line states the declared list', () => {
  assert(progErrors({ ...P.upperHypertrophy.def, stripIntensifierOn: ['taper'] }).includes('literalDomain@stripIntensifierOn.0'), 'taper is not a week of this calendar')
  assert(progErrors({ ...P.upperHypertrophy.def, stripIntensifierOn: ['delaod' as never] }).includes('unknownName@stripIntensifierOn.0'), 'not a week role at all')
  const cx = DS.cxOf(reg)
  assert(DD.describeProgram({ ...P.upperHypertrophy.def, stripIntensifierOn: [] }, cx).some((l) => l === '  No week role drops the intensifier.'), '[] stated')
  assert(DD.describeProgram({ ...P.upperHypertrophy.def, stripIntensifierOn: ['deload'] }, cx).some((l) => l === '  Intensifiers are dropped in deload weeks.'), 'a list stated')
})

// ── C6: the grid-tie direction ──────────────────────────────────────────────

t('', 'C6 (fail-first): ties up sends an exact tie to the upper grid step, in the pinned integer formulation, and only ties move', () => {
  eq(UN.nearestStep(101.25, 2.5, 'up'), 102.5, 'the load tie')
  eq(UN.nearestStep(101.25, 2.5), 100, 'down is unchanged')
  eq(UN.nearestStep(7.5, 1, 'up'), 8, 'a half-rep tie')
  eq(UN.nearestStep(-1.25, 2.5, 'up'), 0, 'a negative tie goes toward +∞')
  eq(UN.nearestStep(101.3, 2.5, 'up'), 102.5, 'a non-tie rounds nearest either way')
  eq(UN.nearestStep(101.2, 2.5, 'up'), 100, 'a non-tie below the midpoint still goes down')
  eq(IS.sinkField({ k: 'fixed', v: { b: 'exact', v: 101.25 } }, 'load', { load: 2.5 }, 'up'), { k: 'fixed', v: { b: 'exact', v: 102.5 } }, 'the sink honours the declared direction')
  eq(IS.sinkField({ k: 'fixed', v: { b: 'atMost', v: 101.25 } }, 'load', { load: 2.5 }, 'up'), { k: 'fixed', v: { b: 'atMost', v: 100 } }, 'a ceiling still goes down: direction law untouched')
})

t('', 'C6 a ties-up program issues the upper step, stamps the declaration, and `round nearest` follows it; the prose states it on the grid line', () => {
  const def = { ...P.linear3x5.def, ties: 'up' as const }
  const run = TK.start(def, {}, TK.factsOf({ e1rm: { 'wger:111': TK.q(121.5, 'kg'), 'wger:192': TK.q(121.5, 'kg'), 'wger:119': TK.q(121.5, 'kg'), 'wger:105': TK.q(121.5, 'kg') } }))
  const x = TK.issue(run, D0)
  eq(TK.loadOf(x.issued, 'squat'), 102.5, 'the 101.25 kg tie lands up')
  eq(x.issued.stamp.ties, 'up', 'stamped: resolution never re-derives')
  const base = TK.start(P.linear3x5.def, {}, TK.factsOf({ e1rm: { 'wger:111': TK.q(121.5, 'kg'), 'wger:192': TK.q(121.5, 'kg'), 'wger:119': TK.q(121.5, 'kg'), 'wger:105': TK.q(121.5, 'kg') } }))
  eq(TK.loadOf(TK.issue(base, D0).issued, 'squat'), 100, 'the default program still lands down')
  eq(TK.issue(base, D0).issued.stamp.ties, undefined, 'and stamps nothing')
  const round: Term = { k: 'round', mode: 'nearest', a: { k: 'lit', lit: { k: 'q', v: 101.25, unit: 'kg' } }, step: { k: 'lit', lit: { k: 'q', v: 2.5, unit: 'kg' } } }
  eq(nOf(EV.evaluate(round, EV.ctxOf(reg, { ties: 'up' })).value), 102.5, 'round nearest follows the program')
  eq(nOf(EV.evaluate(round, EV.ctxOf(reg)).value), 100, 'and stays down by default')
  assert(progErrors({ ...P.linear3x5.def, ties: 'sideways' as never }).includes('unknownName@ties'), 'an unknown direction is refused')
  assert(DD.describeProgram(def, DS.cxOf(reg)).some((l) => l.includes('a target exactly between two grid steps rounds up')), 'the grid line states it')
})

// ── C7: the lapse threshold per instance ────────────────────────────────────

t('', 'C7 (fail-first): an instance-level lapseAfterDays override lapses the instance on the overridden clock, and the spec carries the active value', () => {
  const rt = PO.runtimeOf(reg, ER_C25K(), { id: 'lapse5', anchor: D0, activatedOn: D0, overrides: { lapseAfterDays: 5 } })
  eq(rt.spec.lapseAfterDays, 5, 'the active value')
  let head = ST.activate(rt, {}, TK.factsOf({}))
  for (const e of TI.reconcile(rt.spec, head.calendar, TK.day('2026-10-12'))) {
    const r = ST.step(rt, head, e)
    assert(r.k === 'applied', 'dayClosed applies')
    head = r.head
  }
  eq(head.calendar.status, 'lapsed', '7 untrained days beat the 5-day override')
  const base = PO.runtimeOf(reg, ER_C25K(), { id: 'lapse21', anchor: D0, activatedOn: D0 })
  eq(base.spec.lapseAfterDays, 21, 'no override keeps the program’s declaration')
  assert(DD.describeProgram(ER_C25K(), DS.cxOf(reg)).some((l) => l.includes("If you don't train for 21 days")), 'the program prose states its declared value; the spec carries an instance’s active one')
})

t('', 'C7 negative: a lapse override below one day is refused at the boundary', () => {
  let threw = ''
  try {
    TI.calendarSpecOf(ER_C25K(), [], 'x', D0, D0, { lapseAfterDays: 0 })
  } catch (e) {
    threw = (e as Error).message
  }
  assert(threw.includes('lapseAfterDays'), `refused: ${threw}`)
})

// ── C8: fact staleness per program ──────────────────────────────────────────

t('', 'C8 (fail-first): a program’s staleness override makes a 5-day-old e1RM silence where the registry’s 56-day rule accepts it', () => {
  const facts = TK.factsOf({ e1rm: TK.E1RM }, TK.day('2026-09-30'))
  const strict = TK.start({ ...P.linear3x5.def, staleness: { e1rm: 3 } }, {}, facts)
  const strictLoad = TK.stateOf(strict, 'squat', 'load')
  assert(strictLoad.v === 'none' && strictLoad.cause.k === 'factStale' && strictLoad.cause.maxAgeDays === 3, `stale under the 3-day override: ${JSON.stringify(strictLoad)}`)
  const base = TK.stateOf(TK.start(P.linear3x5.def, {}, facts), 'squat', 'load')
  assert(base.v === 'q', `the registry's 56-day rule still accepts it: ${JSON.stringify(base)}`)
})

t('', 'C8 negatives and prose: an override for an unread or unknown fact, or with bad days, is refused; the freshness line states the rule', () => {
  assert(progErrors({ ...P.linear3x5.def, staleness: { soreness: 1 } }).includes('undeclaredFact@staleness.soreness'), 'a fact nothing reads')
  assert(progErrors({ ...P.linear3x5.def, staleness: { eOneRm: 3 } }).includes('unknownName@staleness.eOneRm'), 'no such fact')
  assert(progErrors({ ...P.linear3x5.def, staleness: { e1rm: 0 } }).includes('literalDomain@staleness.e1rm'), 'zero days')
  const lines = DD.describeProgram({ ...P.linear3x5.def, staleness: { e1rm: 3 } }, DS.cxOf(reg))
  assert(lines.some((l) => l === "  Freshness: your estimated max is ignored once older than 3 days (this program's rule)."), `stated: ${lines.find((l) => l.startsWith('  Freshness'))}`)
  assert(DD.factLine(reg.vocab.facts['e1rm']!, 3).includes('ignored once older than 3 days, by this program'), 'the facts line marks an override where the program declares the fact')
})

// ── C9: scaleSets allowZero ─────────────────────────────────────────────────

const twoLine = (): Parameters<typeof IS.applyUse>[1] => {
  const run = TK.start(ER.achillesLoading.def, {}, TK.factsOf({}))
  const x = TK.issue(run, D0)
  const sl = x.issued.slots[0]!
  return { exercise: { v: 'ref', kind: 'exercise', id: 'heel-drop' }, steps: sl.steps, intensifier: null }
}

const quarter = (s: Parameters<typeof IS.applyUse>[1], allowZero: boolean) => XF.applyXform('scaleSets', s, { v: 'q', n: 0.25, dim: {}, unit: 'pct' }, null, null, null, allowZero)

t('', 'C9 (fail-first): allowZero lets a 25% deload drop a 3-set line to zero sets; the default still floors at one', () => {
  const s = twoLine()
  const zero = quarter(s, true)
  eq(zero.steps.map((st) => (st.count.k === 'n' ? st.count.n : -1)), [0, 0], 'both lines drop to none')
  eq(zero.steps.map((st) => st.sets.length), [0, 0], 'no issued targets either')
  const floored = quarter(s, false)
  eq(floored.steps.map((st) => (st.count.k === 'n' ? st.count.n : -1)), [1, 1], 'the F12 floor holds without the option')
})

t('', 'C9 through the former: a zero-set planned line is judged on nothing (unknown) and counts no volume; the IR option is refused anywhere but scaleSets', () => {
  const session: Term = { k: 'xform', op: 'scaleSets', allowZero: true, s: { k: 'session', exercise: { k: 'lit', lit: { k: 'ref', kind: 'exercise', id: 'wger:111' } }, steps: [{ k: 'step', id: 'w' as never, count: { k: 'n', n: { k: 'lit', lit: { k: 'q', v: 2, unit: 'set' } } }, target: { k: 'set', role: 'working', target: { reps: { b: 'exact', v: { k: 'lit', lit: { k: 'q', v: 5, unit: 'rep' } } } }, rest: null, tempo: null, cluster: null } }], intensifier: null }, arg: { k: 'lit', lit: { k: 'q', v: 0.25, unit: 'pct' } }, metric: null }
  const v = EV.evaluate(session, EV.ctxOf(reg)).value
  assert(v.v === 'session' && v.s.steps[0]!.count.k === 'n' && v.s.steps[0]!.count.n === 0, 'the former honours allowZero')
  eq(JU.verdictOf({ reg, slots: [{ slot: 'x', exercise: { id: 'wger:111', label: 'Squat', logging: 'weight_reps' }, steps: v.v === 'session' ? v.s.steps : [], intensifier: null, trace: { node: session, value: v, kids: [] } }], performed: {}, facts: [], groupScores: {}, week: 0, primary: () => undefined }, 'working', 'floor'), 'unknown', 'zero planned sets judge nothing (never a vacuous hit)')
  eq(check({ ...session, op: 'scaleMetric', metric: 'load', arg: { k: 'lit', lit: { k: 'q', v: 0.9, unit: 'pct' } } } as Term, null, 'handler'), ['literalDomain@allowZero'], 'allowZero is scaleSets’s option alone')
  const prose = DS.describe(session, DS.cxOf(reg))
  assert(prose.includes('(a line may drop to no sets)'), `stated: ${prose}`)
})

// ── C10: library constants promoted to defaulted params ─────────────────────

const cfgRange = program({
  id: 'prog/cfg-range',
  version: 1,
  says: 'config-round worked program: double progression rebased to 5–8',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: { load: kg(2.5) },
  muscles: ['chest'],
  slots: () => ({ bench: doubleProg.bind({ lift: exercise('wger:192'), sets: sets(3), inc: kg(2.5), start: some(kg(60)), lo: reps(5), hi: reps(8) }, { muscles: { chest: 1 } }) }),
  days: { A: [single('bench')] },
  rotation: { k: 'weekly', days: ['A'] },
})

t('', 'C10 (fail-first): a binding may rebase doubleProg’s defaulted 8–12 range; omitting it keeps the old numbers byte for byte', () => {
  const x = TK.issue(TK.start(cfgRange.def, {}, TK.corpusFacts()), D0)
  const f = TK.fieldOf(x.issued, 'bench', 'reps')
  eq(f, { k: 'fixed', v: { b: 'range', min: 5, max: 8 } }, 'the override reaches the issued target')
  const base = TK.issue(TK.start(P.optLoaded.def, { benchStart: { v: 'q', n: 60, dim: { mass: 1 }, unit: 'kg' } }, TK.corpusFacts()), D0)
  eq(TK.fieldOf(base.issued, 'bench', 'reps'), { k: 'fixed', v: { b: 'range', min: 8, max: 12 } }, 'the corpus binding, which omits lo and hi, is unchanged')
  eq(reg.schemes.get('lib/double-progression@1')!.defaults!['lo'], { k: 'lit', lit: { k: 'q', v: 8, unit: 'rep' } }, 'the default is a declared fact of the definition')
})

t('', 'C10 checker: a binding may omit only DEFAULTED params; a default must name a param and match its sort; a hole is only optional for a defaulted param', () => {
  eq(codes(CD.checkScheme(reg.schemes.get('lib/double-progression@1')!, reg)), [], 'the promoted scheme checks clean with holes only for non-defaulted params')
  const s = reg.schemes.get('lib/double-progression@1')!
  assert(!progErrors(cfgRange.def).length, 'binding the defaulted params is fine')
  const noLift = { ...cfgRange.def, slots: { bench: { ...cfgRange.def.slots['bench']!, args: Object.fromEntries(Object.entries(cfgRange.def.slots['bench']!.args).filter(([k]) => k !== 'lift')) } } }
  assert(progErrors(noLift).includes('missingArg@slots.bench.args'), 'a non-defaulted param still must be bound')
  const badDefault = { ...s, ref: { ...s.ref, id: 'lib/dp-bad' as never }, defaults: { nope: { k: 'lit', lit: { k: 'q', v: 1, unit: 'rep' } } as Term } }
  assert(codes(CD.checkScheme(badDefault, reg)).includes('unknownName@defaults.nope'), 'a default for a non-param')
  const wrongTy = { ...s, ref: { ...s.ref, id: 'lib/dp-bad2' as never }, defaults: { ...s.defaults, lo: { k: 'lit', lit: { k: 'q', v: 8, unit: 'kg' } } as Term } }
  assert(codes(CD.checkScheme(wrongTy, reg)).includes('unitMismatch@defaults.lo'), 'a default of the wrong sort')
  const noHole = { ...s, ref: { ...s.ref, id: 'lib/dp-bad3' as never }, defaults: {} }
  assert(codes(CD.checkScheme(noHole as never, reg)).some((c) => c.startsWith('templateHoles')), 'without the default the missing holes are refused again')
})

t('', 'C10 prose: a non-default argument for a hole-less defaulted param is appended, so the template never lies by silence; defaults render nothing', () => {
  const lines = DD.describeProgram(cfgRange.def, DS.cxOf(reg))
  const slotLine = lines.find((l) => l.trimStart().startsWith('bench:'))!
  assert(slotLine.includes('(with lo = 5 reps, hi = 8 reps)'), `the override is stated: ${slotLine}`)
  const base = DD.describeProgram(P.optLoaded.def, DS.cxOf(reg))
  assert(!base.join('\n').includes('(with '), 'an omitted default appends nothing')
})

const cfgJokers = program({
  id: 'prog/cfg-jokers',
  version: 1,
  says: 'config-round worked program: jokers jumping 10%',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: { load: kg(2.5) },
  muscles: ['quads'],
  slots: () => ({ main: w531Jokers.bind({ lift: SQUAT, tm: some(kg(100)), jokerStep: pct(110) }, { muscles: { quads: 1 } }) }),
  days: { A: [single('main')] },
  rotation: { k: 'weekly', days: ['A'] },
})

const cfgJokersDefault = program({
  id: 'prog/cfg-jokers-default',
  version: 1,
  says: 'config-round worked program: jokers at the default step',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: { load: kg(2.5) },
  muscles: ['quads'],
  slots: () => ({ main: w531Jokers.bind({ lift: SQUAT, tm: some(kg(100)) }, { muscles: { quads: 1 } }) }),
  days: { A: [single('main')] },
  rotation: { k: 'weekly', days: ['A'] },
})

t('', 'C10 the joker step is live: logging the top set resolves the first joker at the DECLARED 110%, and at the default 105% when omitted', () => {
  const resolveJoker = (def: typeof cfgJokers.def) => {
    const x = TK.issue(TK.start(def, {}, TK.corpusFacts()), D0)
    const logged = { main: { s1: [{ values: { reps: 5, load: 65 }, stages: null }], s2: [{ values: { reps: 5, load: 75 }, stages: null }], s3: [{ values: { reps: 6, load: 85 }, stages: null }] } }
    const rows = IS.resolveLive({ reg }, x.issued, logged, [])
    return rows.find((r) => r.step === 'joker' && r.index === 0 && r.metric === 'load')
  }
  const declared = resolveJoker(cfgJokers.def)
  assert(declared && declared.value.k === 'fixed' && declared.value.v.b === 'exact', 'the joker resolves')
  eq(declared.value.v, { b: 'exact', v: 92.5 }, '85 × 110% = 93.5, sunk to the 2.5 kg grid (nearest, ties down)')
  const dflt = resolveJoker(cfgJokersDefault.def)
  assert(dflt && dflt.value.k === 'fixed', 'the default binding resolves too')
  eq(dflt.value.v, { b: 'exact', v: 90 }, '85 × 105% = 89.25, sunk to 90')
})

// ── C11: the viewer display unit, projection layer only ─────────────────────

t('', 'C11 (fail-first): sessionText takes a viewer unit and renders every mass in it, display-exactly; nothing in the issued fact moves', () => {
  const run = TK.start(P.linear3x5.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  const kgLines = DR.sessionText(x.issued, reg)
  const lbLines = DR.sessionText(x.issued, reg, { mass: 'lb' })
  assert(kgLines.some((l) => l.includes('117.5 kg')), `the program’s unit by default: ${kgLines[1]}`)
  assert(lbLines.some((l) => l.includes('259.043 lb')), `the viewer’s unit on demand (117.5 kg, display-exact to the locale’s three decimals): ${lbLines[1]}`)
  eq(lbLines.length, kgLines.length, 'same prose shape')
  eq(TK.loadOf(x.issued, 'squat'), 117.5, 'the issued number is untouched: conversion is display only, never re-quantized')
  eq(DR.sessionText(x.issued, reg, {}), kgLines, 'an empty viewer changes nothing')
})

/** c25k's def (ER namespace is loaded via testkit's corpus registry). */
function ER_C25K() {
  const d = reg.programs.get('prog/c25k@1')
  if (!d) throw new Error('c25k is not published')
  return d
}

done()
