/**
 * dispose.ts — generates ../design/corpus/test-plan-disposition.md from what
 * RAN: every EC/BV row of the test plan is `covered` by the passing tests that
 * name it (semantics, laws, conformance, differential) or by the suites that
 * already covered it (negative.ts, demo, tsc), else `re-homed` or `waived`
 * with the reason in dispositions.ts. A row with none of these, or covered
 * only by a failing test, fails the run. Run: QUIET=1 tsx dispose.ts [--write]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { RESULTS } from './testkit'
import './semantics.test'
import './laws.test'
import './conformance'
import { MANUAL, SPEC_DECISIONS } from './dispositions'

declare const process: { argv: string[]; exitCode?: number }
const PLAN = new URL('../design/corpus/test-plan.md', import.meta.url)
const OUT = new URL('../design/corpus/test-plan-disposition.md', import.meta.url)

interface Row {
  id: string
  cls: string
  cov: string
  spec: boolean
}
const rows: Row[] = readFileSync(PLAN, 'utf8')
  .split('\n')
  .filter((l) => /^\| (EC|BV)-(C?\d+)/.test(l))
  .map((l) => {
    const cells = l.split('|').map((c) => c.trim())
    const id = cells[1]!
    const isBV = id.startsWith('BV')
    return { id, cls: (isBV ? `${cells[2]}: ${cells[3]}` : cells[2]!).replace(/\*\*/g, ''), cov: cells[cells.length - 2]!, spec: l.includes('SPEC?') }
  })

const byId = new Map<string, { ok: string[]; failed: string[] }>()
for (const r of RESULTS)
  for (const id of r.ids) {
    const e = byId.get(id) ?? { ok: [], failed: [] }
    ;(r.ok ? e.ok : e.failed).push(`${r.suite}: ${r.name}`)
    byId.set(id, e)
  }
const EXISTING: Record<string, string> = { N: 'negative.ts', D: 'demo.out.txt', T: 'tsc (a mapped type)' }

const out: string[] = []
const counts = { covered: 0, 'covered (existing)': 0, 're-homed': 0, waived: 0, missing: 0 }
const problems: string[] = []
for (const r of rows) {
  const tests = byId.get(r.id)
  const manual = MANUAL[r.id]
  const spec = r.spec ? SPEC_DECISIONS[r.id] : undefined
  if (r.spec && !spec) problems.push(`${r.id}: SPEC? row with no law decision`)
  if (tests?.failed.length) problems.push(`${r.id}: covered by a FAILING test (${tests.failed.join('; ')})`)
  let disp: string
  let where: string
  if (tests?.ok.length) {
    disp = 'covered'
    const cut = (x: string) => (x.length > 90 ? `${x.slice(0, 89)}…` : x)
    where = tests.ok.slice(0, 2).map((n) => `${n.split(':')[0]}: “${cut(n.slice(n.indexOf(':') + 2))}”`).join('; ') + (tests.ok.length > 2 ? `; and ${tests.ok.length - 2} more` : '')
    counts.covered++
  } else if (manual) {
    disp = manual.d
    where = manual.why
    counts[manual.d === 'covered' ? 'covered (existing)' : manual.d]++
  } else if (/\b(N|D|T)\b/.test(r.cov) && !/GAP/.test(r.cov)) {
    disp = 'covered'
    where = `existing: ${[...new Set([...r.cov.matchAll(/\b(N|D|T)\b/g)].map((m) => EXISTING[m[1]!]))].join(', ')}`
    counts['covered (existing)']++
  } else {
    disp = 'MISSING'
    where = ''
    counts.missing++
    problems.push(`${r.id}: no disposition`)
  }
  out.push(`| ${r.id} | ${r.cls.replace(/\|/g, '/')} | ${disp} | ${where}${spec ? ` **Decided:** ${spec}` : ''} |`)
}

const total = rows.length
const doc = [
  '# Test-plan disposition (R2)',
  '',
  'Generated by `arena2/synthesis/dispose.ts` from the tests that RAN (`verify.sh` step 7 regenerates and diffs it). Do not edit by hand: change a test, or `dispositions.ts` for a re-home or waiver.',
  '',
  `**Counts.** ${total} rows (EC, BV and the corpus-pending EC-C rows). Covered by an R2 test: ${counts.covered}. Covered by a suite that already existed (negative.ts, demo, tsc): ${counts['covered (existing)']}. Re-homed: ${counts['re-homed']}. Waived: ${counts.waived}. Missing: ${counts.missing}.`,
  '',
  `**SPEC? rows.** ${rows.filter((r) => r.spec).length}, each decided below (the one-line law is in rationale.md, "R2 law decisions").`,
  '',
  '`covered` names the suite and the passing tests that name the row (up to two, then a count). A test names its rows in its first argument (`t(\'EC-45 BV-38\', …)`), so this table is what the suites claim and passed, not what someone remembered.',
  '',
  '| ID | Class | Disposition | Where / why |',
  '|---|---|---|---|',
  ...out,
  '',
]
const text = doc.join('\n')
if (process.argv.includes('--write')) writeFileSync(OUT, text)
else {
  const have = (() => {
    try {
      return readFileSync(OUT, 'utf8')
    } catch {
      return ''
    }
  })()
  if (have !== text) problems.push('test-plan-disposition.md is stale: run QUIET=1 tsx dispose.ts --write')
}
for (const p of problems) console.log(`  ${p}`)
console.log(`7. disposition: ${total} rows; ${counts.covered} covered by R2 tests, ${counts['covered (existing)']} by existing suites, ${counts['re-homed']} re-homed, ${counts.waived} waived, ${counts.missing} missing; ${problems.length} problems`)
if (problems.length) process.exitCode = 1
