/**
 * patfix.test.ts — the correctness interrogation round (patrev-a/-b/-c): the
 * reviewer probes as regressions. Modules are imported as namespaces, as in
 * semfix.test.ts, so a test that needs what the pre-round oracle lacks fails
 * alone; the fail-first run against synthesis-weekbasis is
 * ../patfix-prefix.txt (regenerated by ../patfix-prefix.sh).
 * Run: tsx patfix.test.ts
 */
import { kg, muscle, reps, rir, type Term } from './algebra'
import { canonicalJson } from './canonical'
import * as CK from './checker'
import * as CKdefs from './checkdefs'
import type { Event, Value } from './engine'
import * as EV from './evaluate'
import type { AggRead } from './evaluate'
import { eventPort } from './judge'
import * as P from './programs'
import * as PO from './ports'
import * as ST from './step'
import * as TI from './time'
import * as TK from './testkit'
import { aggQ, type ProgramDef, type WeeklyOpts } from './structure'

const { t, done } = TK.suite('patfix')
const assert: (ok: unknown, msg: string) => asserts ok = TK.assert
const { eq, near, reg, D0 } = TK
const d = (n: number) => TI.addDays(D0, n)
const dayEv = (inst: string, n: number): Event => ({ k: 'dayClosed', causeKey: `day:${inst}:${d(n)}`, day: d(n) }) as Event
const chest = { k: 'muscle', id: 'chest' } as const
const nOf = (v: Value): number => (v.v === 'q' ? v.n : NaN)

// ── X1: a default weekly read past the end of a `once` program ──────────────
// patrev-c p2/p2c and patrev-a p2: the role===null absence return ran for
// EVERY weekly read, so a DEFAULT read (typed plain) produced a none and the
// evaluator crashed ("expected a quantity, got none").

const RP = P.rpMeso.def
const rpDone = () => TK.train(TK.start(RP), 10, D0).run
const weekly = (run: ReturnType<typeof rpDone>, opts: Partial<Extract<AggRead, { q: 'weekly' }>> = {}): Value =>
  PO.aggPort(run.rt, run.ledger.head, { facts: TK.factsOf({}), today: D0, earlierToday: 0, reads: PO.newReads() })({ q: 'weekly', metric: 'sets', by: chest, ...opts })

t('', 'X1: at week == len of a `once` program a DEFAULT weekly read evaluates to a plain quantity; `upcoming` there is still noUpcomingWeek', () => {
  const run = rpDone()
  eq(run.ledger.head.progress.week, RP.calendar.weeks.length, 'the program ran past its last week')
  const def = weekly(run)
  assert(def.v === 'q', `a default read is a quantity, never a none: got ${JSON.stringify(def)}`)
  eq(weekly(run, { basis: 'upcoming' }), { v: 'none', cause: { k: 'noUpcomingWeek' } }, 'upcoming keeps its typed absence')
  eq(weekly(run, { roles: ['accumulation'] }), { v: 'none', cause: { k: 'roleExcluded', role: 'train' } }, 'a filtered read keeps the pre-round ?? train role as its gate')
})

t('', 'X1: a periodClosed handler with a default weekly read runs past completion without throwing (patrev-c p2c)', () => {
  const aggT: Term = { k: 'agg', q: { q: 'weekly', metric: 'sets', by: { k: 'muscle', of: { k: 'lit', lit: { k: 'ref', kind: 'muscle', id: 'chest' } } } } } as Term
  const lit0: Term = { k: 'lit', lit: { k: 'q', v: 0, unit: 'set' } } as Term
  const keep: Term = { k: 'patch', set: {} } as Term
  const body: Term = { k: 'if', c: { k: 'cmp', op: '>', a: { k: 'arith', op: '+', a: { k: 'var', name: 'v' }, b: lit0 }, b: lit0 }, a: keep, b: keep } as Term
  const handler: Term = { k: 'let', name: 'v', label: 'probe', value: aggT, body } as Term
  const def2 = { ...RP, aggregate: { ...RP.aggregate!, on: { periodClosed: handler } } } as ProgramDef
  const run = TK.train(TK.start(def2), 10, D0).run
  eq(run.ledger.head.status, 'completed', 'completed')
  let l = run.ledger
  for (let n = 0; n <= 40; n++) l = ST.ingest(run.rt, l, dayEv(run.rt.spec.instance, n)).ledger
  const fired = l.transitions.flatMap((tr) => tr.fired).filter((f) => f.scope === 'program' && f.on === 'periodClosed')
  assert(fired.length > 0 && fired.every((f) => f.reason !== null), 'every periodClosed handler evaluated its default read')
})

// ── X2: batched dayClosed ≡ daily dayClosed (L5) ────────────────────────────
// patrev-a p1 (adjudicated by the parent) and patrev-c p1: per-day side
// effects were applied from the LAST day's state, so a batched catch-up and
// day-by-day closing diverged on an anchored calendar.

/** The delivery-independent view of a run: seq numbers count events, so they
 *  are stripped; everything else must match across deliveries. */
const summary = (l: ST.Ledger): string => {
  const strip = (x: unknown): unknown =>
    Array.isArray(x) ? x.map(strip) : x && typeof x === 'object' ? Object.fromEntries(Object.entries(x).filter(([k]) => k !== 'seq').map(([k, v]) => [k, strip(v)])) : x
  const h = l.head
  return canonicalJson(
    strip({
      state: h.state,
      progress: h.progress,
      status: h.status,
      pending: h.pending,
      cal: { ...h.calendar, seen: [...h.calendar.seen].sort() },
      emitted: l.transitions.flatMap((tr) => tr.emitted),
      fired: l.transitions.flatMap((tr) => tr.fired.map((f) => ({ scope: f.scope, on: f.on, causeKey: f.causeKey, patch: f.patch, skipped: f.skipped ?? null }))),
    }),
  )
}
const closeThrough = (def: ProgramDef, splits: number[], last: number, pause: { from: number; until: number | null } | null): ST.Ledger => {
  const run = TK.start(def, {}, TK.corpusFacts())
  let l = run.ledger
  if (pause) l = ST.ingest(run.rt, l, { k: 'pause', causeKey: 'pause:x', from: d(pause.from), until: pause.until === null ? null : d(pause.until) } as Event).ledger
  for (const n of [...splits, last]) l = ST.ingest(run.rt, l, dayEv(run.rt.spec.instance, n)).ledger
  return l
}

t('', 'X2: anchored drift with a future pause: one batched dayClosed lands on the same state and emits the same closes as daily delivery (patrev-a p1)', () => {
  const def = { ...P.linear3x5.def, calendar: { ...P.linear3x5.def.calendar, drift: 'anchored' } } as ProgramDef
  const daily = closeThrough(def, [0, 1, 2, 3, 4, 5, 6, 7], 8, { from: 8, until: null })
  const batched = closeThrough(def, [], 8, { from: 8, until: null })
  const weekCloses = (l: ST.Ledger) => l.transitions.flatMap((tr) => tr.emitted).filter((k) => k.startsWith('week'))
  eq(weekCloses(daily).length, 1, 'daily delivery closes block week 0 on its anchored day')
  eq(weekCloses(batched), weekCloses(daily), 'batched delivery emits the same week close')
  eq(summary(batched), summary(daily), 'indistinguishable terminal state')
})

t('', 'X2: any split of the same day range lands on the same terminal state and closes (L5 replay determinism, patrev-c p1)', () => {
  const def = { ...P.linear3x5.def, calendar: { weeks: ['train', 'train', 'train', 'train'], repeat: 'cycle', drift: 'anchored' } } as ProgramDef
  const want = summary(closeThrough(def, Array.from({ length: 40 }, (_, i) => i), 40, { from: 9, until: 13 }))
  for (const splits of [[], [5], [13, 27], [6, 7, 20, 33], [8, 9, 10, 14]])
    eq(summary(closeThrough(def, splits, 40, { from: 9, until: 13 })), want, `split at [${splits.join(', ')}] is indistinguishable from daily delivery`)
})

// ── X3: the embedding types a widened-options weekly read as Opt ────────────
// patrev-a p3 / patrev-c p2b: the IR types it Opt, so the embedding must too
// (the @ts-expect-error twin is in negative.ts). The converse direction, that
// IR-accepted known(...) handling typechecks, is the line below: it compiles.
const widened: WeeklyOpts = { basis: 'upcoming' }
t('', 'X3: a widened-options read lowers to the same IR and the checker types it Opt (the embedding now agrees: see negative.ts)', () => {
  const read = aggQ.setsFor(muscle('chest'), 'muscle', widened)
  const sc = CK.baseScope(reg, 'aggregate', {}, { id: 'demo/patfix', seq: reg.seq.size })
  const out: import('./engine').TypeError[] = []
  const r = CK.top(read.term, sc, [], null, out)
  eq(out.length, 0, 'accepted')
  eq(r?.ty, { t: 'opt', of: { t: 'q', dim: { set: 1 } } }, 'Opt in the IR, as in the embedding')
})

// ── X4: a roles filter disjoint from a KNOWN calendar is refused ────────────
// patrev-a p5: a filter naming only roles the calendar never has was silently
// dead (absent every week); the checker now refuses it (literalDomain).

t('', 'X4: a roles list disjoint from the program calendar’s role set is literalDomain; RP as written still checks clean', () => {
  const errs = (p: ProgramDef) => CKdefs.checkProgram(p, reg).flatMap((x) => x.errors)
  const bad = JSON.parse(JSON.stringify(RP).replace('"roles":["accumulation"]', '"roles":["realization"]')) as ProgramDef
  assert(errs(bad).some((e) => e.code === 'literalDomain' && e.path.join('.').includes('roles')), `a disjoint filter is refused: ${JSON.stringify(errs(bad).map((e) => e.code))}`)
  eq(errs(RP).length, 0, 'the declared filter (accumulation, a calendar role) is accepted')
})

// ── X5: lapse across a bounded pause ────────────────────────────────────────
// patrev-a p7 / patrev-c p3: the day a pause ended, a lapsed-with-no-training
// instance read `active` for one day before re-lapsing.

const SPEC = (lapseAfterDays = 21): TI.CalendarSpec => ({
  instance: 'i',
  anchor: D0,
  activatedOn: D0,
  frequency: [{ k: 'atLeast', n: 3, of: { s: 'any' }, per: { k: 'week' } }],
  slots: {},
  lapseAfterDays,
  tracked: [{ s: 'any' }],
})
const closeTo = (spec: TI.CalendarSpec, st: TI.CalendarState, n: number): TI.CalendarState => {
  for (const e of TI.reconcile(spec, st, d(n + 1))) st = TI.stepCalendar(spec, st, e)
  return st
}

t('', 'X5: a bounded pause never launders a lapsed instance into an `active` day: the day the pause ends it is lapsed again (patrev-a p7)', () => {
  const spec = SPEC()
  let st = TI.activate(spec)
  st = closeTo(spec, st, 24)
  eq(st.status, 'lapsed', 'no training for 25 days: lapsed')
  st = TI.stepCalendar(spec, st, { k: 'pause', causeKey: 'pause:1', from: d(25), until: d(26) })
  const statuses: string[] = []
  for (let n = 25; n <= 29; n++) {
    st = closeTo(spec, st, n)
    statuses.push(st.status)
  }
  assert(!statuses.includes('active'), `never active with no training: ${JSON.stringify(statuses)}`)
  eq(st.status, 'lapsed', 'lapsed once the pause ends')
  st = closeTo(spec, st, 40)
  eq(st.status, 'lapsed', 'still lapsed at day 40')
})

t('', 'X5 guard (patrev-b probe4a): the lapse fires on exactly the 21st unpaused day; a 10-day pause defers it 10 days; overlapping pauses count once', () => {
  const mk = () => {
    const run = TK.start(P.linear3x5.def)
    return { rt: run.rt, ledger: run.ledger }
  }
  const lapsedAt = (pauses: { from: number; until: number }[]): number => {
    const r = mk()
    let l = r.ledger
    for (const [i, p] of pauses.entries()) l = ST.ingest(r.rt, l, { k: 'pause', causeKey: `pause:p${i}`, from: d(p.from), until: d(p.until) } as Event).ledger
    for (let n = 0; n <= 60; n++) {
      l = ST.ingest(r.rt, l, dayEv(r.rt.spec.instance, n)).ledger
      if (l.head.calendar.status === 'lapsed') return n
    }
    return -1
  }
  eq(lapsedAt([]), 21, 'no pause: lapsed closing day 21')
  eq(lapsedAt([{ from: 5, until: 14 }]), 31, 'a 10-day pause defers the lapse by exactly 10 days')
  eq(lapsedAt([{ from: 5, until: 14 }, { from: 8, until: 14 }]), 31, 'overlapping pauses do not double-count')
})

t('', 'X5 guard (patrev-b probe4b): one catch-up dayClosed through a pause lands on the day-by-day state; a regressed day closes nothing again', () => {
  const steps = TK.start(P.linear3x5.def)
  let sl = steps.ledger
  sl = ST.ingest(steps.rt, sl, { k: 'pause', causeKey: 'pause:p1', from: d(5), until: d(14) } as Event).ledger
  for (let n = 0; n <= 35; n++) sl = ST.ingest(steps.rt, sl, dayEv(steps.rt.spec.instance, n)).ledger
  const jump = TK.start(P.linear3x5.def)
  let jl = jump.ledger
  jl = ST.ingest(jump.rt, jl, { k: 'pause', causeKey: 'pause:p1', from: d(5), until: d(14) } as Event).ledger
  jl = ST.ingest(jump.rt, jl, dayEv(jump.rt.spec.instance, 35)).ledger
  eq(jl.head.calendar.status, sl.head.calendar.status, 'same status (lapsed) either way')
  eq(summary(jl), summary(sl), 'same delivery-independent state')
  jl = ST.ingest(jump.rt, jl, dayEv(jump.rt.spec.instance, 10)).ledger
  eq(jl.head.calendar.status, sl.head.calendar.status, 'a regressed day closes nothing again')
})

// ── X6: one e1RM rule, event path and inverse ───────────────────────────────
// The event-path Epley ignored logged RIR while lib/load-for's inverse
// included it, so a round trip disagreed. One rule now (OWNER-OVERRIDABLE:
// the RIR treatment; the formula family is a pending owner choice).

t('', 'X6: the event e1RM counts logged reps in reserve as reps (asReps), so loadFor round-trips it exactly; an unlogged effort adds nothing', () => {
  const x = TK.issue(TK.start(P.linear3x5.def, {}, TK.corpusFacts()), D0, TK.corpusFacts())
  const port = (values: Record<string, number>) =>
    eventPort({
      reg,
      slots: x.issued.slots.filter((s) => s.slot === 'squat'),
      performed: { squat: { work: [{ values, stages: null }] } },
      facts: [],
      groupScores: {},
      week: 0,
      primary: () => 'quads',
    })({ q: 'e1rm', step: 'work' as never })
  near(nOf(port({ reps: 5, load: 100, effort: 2 })), 100 * (1 + 7 / 30), 'Epley sees reps + RIR')
  near(nOf(port({ reps: 5, load: 110 })), 110 * (1 + 5 / 30), 'an unlogged effort adds nothing')
  const e = nOf(port({ reps: 5, load: 100, effort: 2 }))
  const back = TK.ev(P.loadFor({ e1rm: kg(e), reps: reps(5), rir: rir(2) }))
  assert(back.v === 'q' && Math.abs(back.n - 100) < 1e-9, `the inverse returns the logged load: ${JSON.stringify(back)}`)
})

// ── D3 / B N3: the capture walk evaluates a static subterm once ─────────────

t('', 'N3: issue-time capture evaluates a static binder value ONCE, so a world read’s source call is never recorded twice', () => {
  const lit = (v: number, unit: string): Term => ({ k: 'lit', lit: { k: 'q', v, unit: unit as never } }) as Term
  const ref = (id: string): Term => ({ k: 'lit', lit: { k: 'ref', kind: 'exercise', id } }) as Term
  const live = (metric: string): Term => ({ k: 'orElse', a: { k: 'performed', step: 'top' as never, metric, pick: 'last' }, b: lit(0, metric === 'reps' ? 'rep' : 'kg') }) as Term
  let calls = 0
  const term: Term = {
    k: 'if',
    c: { k: 'cmp', op: '>', a: live('reps'), b: lit(5, 'rep') },
    a: { k: 'let', name: 'e', label: 'x', value: { k: 'fact', fact: 'e1rm', key: ref('wger:111') }, body: { k: 'arith', op: 'max', a: { k: 'orElse', a: { k: 'var', name: 'e' }, b: lit(0, 'kg') }, b: live('load') } },
    b: lit(20, 'kg'),
  } as Term
  const ctx = EV.ctxOf(reg, { ports: { fact: () => (calls++, EV.qv(100, { mass: 1 }, 'kg')), performed: () => [], prescribed: () => null } })
  const fd = EV.boundField({ b: 'exact', v: term }, ctx, [])
  eq(fd.k, 'open', 'the field is open (a live read)')
  eq(calls, 1, 'the static fact read was evaluated once, not re-run by the binder')
})

done()
