/**
 * ufx.test.ts — the interrogation repair round (Z1–Z16): the three
 * adversarial reviewers' probes over the configurability-fix and units
 * rounds (ufxrev-a/b/c), ported as named regressions. Modules are imported
 * as namespaces so a test that needs what the frozen pre-round oracle lacks
 * fails alone; the fail-first run against synthesis-units/ is
 * ../ufx-prefix.txt (regenerated by ../ufx-prefix.sh, which labels each
 * failure BEHAVIORAL or API-ABSENT per Z14). Run: tsx ufx.test.ts
 */
import { add, byVerdict, exercise, kg, lb, mul, none, num, pct, reps, rir, sets, ty, type Term } from './algebra'
import { canonicalJson } from './canonical'
import * as CD from './checkdefs'
import * as DS from './describe'
import * as DR from './describe-run'
import * as DD from './describe-defs'
import type { TypeError, Value } from './engine'
import * as ER from './endurance-rehab'
import * as EV from './evaluate'
import * as IS from './issue'
import * as JU from './judge'
import * as P from './programs'
import * as PJ from './project'
import * as PO from './ports'
import * as ST from './step'
import { program, scheme, session, set, single } from './structure'
import * as TI from './time'
import * as TK from './testkit'
import * as UN from './units'

const { t, done } = TK.suite('ufx')
const assert: (ok: unknown, msg: string) => asserts ok = TK.assert
const { eq, near, reg, D0 } = TK
const codes = (es: readonly TypeError[]) => es.map((e) => `${e.code}@${e.path.join('.')}`)
const progErrors = (def: Parameters<typeof CD.checkProgram>[0], r = reg) => codes(CD.checkProgram(def, r).flatMap((x) => x.errors))
const SQUAT = exercise('wger:111')
const lit = (v: number, unit: string): Term => ({ k: 'lit', lit: { k: 'q', v, unit } }) as Term

// ── Z1: program immutability (A-C2, C-1) ────────────────────────────────────

const REBOUND = ['prog/gzclp-t1', 'prog/opt-strength-endurance', 'prog/opt-loaded', 'prog/opt-power', 'prog/legs-3x', 'prog/hr-tempo-block', 'prog/achilles-loading']

t('', 'Z1: the seven rebound programs republish as @2; @1 keeps its published body, binding the @1 schemes (byte-exactness vs the recorded kits: ../cmp-progs-v1.ts)', () => {
  for (const id of REBOUND) {
    const v1 = reg.programs.get(`${id}@1`)
    const v2 = reg.programs.get(`${id}@2`)
    assert(v1, `${id}@1 is published`)
    assert(v2, `${id}@2 is published`)
    for (const b of Object.values(v1.slots)) assert(b.scheme.version === 1 || !['lib/gzclp-t1', 'lib/double-progression', 'lib/531-jokers', 'lib/hr-tempo', 'lib/pain-gated-loading'].includes(b.scheme.id), `${id}@1 binds no @2 scheme`)
    assert(Object.values(v2.slots).some((b) => b.scheme.version === 2), `${id}@2 carries the rebinding`)
    assert(canonicalJson(v1) !== canonicalJson(v2), `${id}: the two versions differ`)
  }
  // The macros that phase into the rebound programs republish the same way.
  for (const id of ['macro/opt-16wk', 'macro/achilles-return']) {
    const m1 = reg.macros.get(`${id}@1`)
    const m2 = reg.macros.get(`${id}@2`)
    assert(m1 && m2, `${id} @1 and @2 are published`)
    assert(m1.phases.every((ph) => !REBOUND.includes(ph.program.id) || ph.program.version === 1), `${id}@1 phases bind the @1 programs`)
    assert(m2.phases.some((ph) => ph.program.version === 2), `${id}@2 phases bind the @2 programs`)
  }
})

t('', 'Z1: publish() REFUSES a changed body at an existing (id, version) — immutability is enforcement, not convention; an identical body stays a no-op', () => {
  const changed = { ...P.linear3x5.def, says: 'a different body under the same version' }
  let refusal: TypeError | null = null
  try {
    CD.publish([P.linear3x5, changed])
  } catch (e) {
    refusal = (e as { refusal?: TypeError }).refusal ?? null
  }
  assert(refusal && refusal.code === 'republishChanged', `the typed refusal: ${JSON.stringify(refusal)}`)
  const r = CD.publish([P.linear3x5, P.linear3x5.def])
  assert(r.programs.get('prog/linear-3x5@1'), 'the identical duplicate is a no-op')
})

// ── Z2: one form per meaning, per entry (A-C1, C-3, B-W2) ───────────────────

t('', 'Z2 (fail-first, A-p1): a record option entry spelling its own default is refused PER ENTRY, even beside a differing sibling', () => {
  const base = P.linear3x5.def
  assert(progErrors({ ...base, volumeWeights: { stage: 0.5, cluster: 0.8 } }).includes('literalDomain@volumeWeights.stage'), 'the stage entry at its default')
  eq(progErrors({ ...base, volumeWeights: { cluster: 0.8 } }), [], 'the minimal spelling checks clean')
  const maxAge = reg.vocab.facts['e1rm']!.maxAgeDays!
  assert(progErrors({ ...base, staleness: { e1rm: maxAge } }).includes('literalDomain@staleness.e1rm'), `a staleness entry at the registry's maxAgeDays`)
  eq(progErrors({ ...base, staleness: { e1rm: maxAge + 4 } }), [], 'a differing entry checks clean')
})

t('', 'Z2 (fail-first, A-p1): maxReps AT the formula’s domain max binds nothing — >= refuses the edge the > check let through', () => {
  assert(progErrors({ ...P.linear3x5.def, e1rm: { formula: 'brzycki', maxReps: 36 } }).includes('literalDomain@e1rm.maxReps'), 'the edge')
  eq(progErrors({ ...P.linear3x5.def, e1rm: { formula: 'brzycki', maxReps: 35 } }), [], 'below the edge binds and is legal')
})

const stripProg = (strip?: string[]) =>
  program({
    id: 'prog/ufx-strip',
    version: 1,
    says: 'x',
    params: {},
    calendar: { weeks: ['train', 'deload'], repeat: 'cycle' },
    grids: { load: kg(2.5) },
    muscles: ['quads'],
    slots: () => ({ squat: P.linearGated.bind({ lift: SQUAT, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { quads: 1 } }) }),
    days: { A: [single('squat')] },
    rotation: { k: 'weekly', days: ['A'] },
    ...(strip ? { stripIntensifierOn: strip as never } : {}),
  }).def

t('', 'Z2 (fail-first, A-p1/C-p9): a strip list equal IN EFFECT to the default (intersected with the calendar’s roles) is a second form and is refused', () => {
  assert(progErrors({ ...stripProg(), stripIntensifierOn: ['deload'] as never }).includes('literalDomain@stripIntensifierOn'), `['deload'] on a train/deload calendar means what omission means`)
  eq(progErrors({ ...stripProg(), stripIntensifierOn: [] as never }), [], `[] (never strip) still differs from the default there`)
  eq(stripProg(['deload'])!.stripIntensifierOn, undefined, 'the embedding drops the default-in-effect spelling')
})

t('', 'Z2 (fail-first, B nit): labels {} spells no labels and is refused like defaults {}', () => {
  const s = reg.schemes.get('lib/double-progression@2')!
  assert(codes(CD.checkScheme({ ...s, ref: { ...s.ref, id: 'lib/ufx-l' as never }, labels: {} }, reg)).includes('literalDomain@labels'), 'labels {}')
})

// A scheme whose handler reads ev.e1rm with an EXPLICIT formula, for the
// read-level one-form law (the explicit spelling of the program's effective
// formula is a second form).
const readFormula = (id: string, formula: 'brzycki' | 'epley') =>
  scheme({
    id,
    version: 1,
    says: 'estimates off {lift}',
    params: { lift: ty.exercise('weight_reps') },
    state: { m: ty.opt(ty.q('mass')) },
    writableBy: { m: ['session', 'owner'] },
    init: () => ({ m: none(ty.q('mass')) }),
    plan: (c) => session({ exercise: c.p.lift, steps: (b) => void b.step('w', sets(3), set({ target: { reps: reps(5) } })) }),
    on: { session: (c) => c.commit({ m: c.ev.e1rm('w', formula) }) },
  })
const bindReadFormula = (sid: string, e1rm?: { formula: 'brzycki' | 'mayhew' }) =>
  program({
    id: 'prog/ufx-formula',
    version: 1,
    says: 'x',
    params: {},
    calendar: { weeks: ['train'], repeat: 'cycle' },
    grids: { load: kg(2.5) },
    muscles: ['quads'],
    slots: () => ({ x: { scheme: { id: sid, version: 1 }, args: { lift: SQUAT.term }, meta: { muscles: { quads: 1 } } } }) as never,
    days: { A: [single('x')] },
    rotation: { k: 'weekly', days: ['A'] },
    ...(e1rm ? { e1rm } : {}),
  }).def

t('', 'Z2 (fail-first, A-C1): an explicit read-level formula equal to the program’s EFFECTIVE formula is refused; one that differs stays legal', () => {
  const sb = readFormula('lib/ufx-read-brzycki', 'brzycki')
  const se = readFormula('lib/ufx-read-epley', 'epley')
  const lreg = CD.publish([...P.PUBLISHED, ...ER.PUBLISHED, sb, se])
  assert(progErrors({ ...bindReadFormula('lib/ufx-read-brzycki', { formula: 'brzycki' }) }, lreg).some((c) => c.startsWith('literalDomain@slots.x')), 'explicit brzycki under a brzycki program')
  eq(progErrors({ ...bindReadFormula('lib/ufx-read-brzycki', { formula: 'mayhew' }) }, lreg), [], 'explicit brzycki under a mayhew program differs: legal')
  assert(progErrors({ ...bindReadFormula('lib/ufx-read-epley') }, lreg).some((c) => c.startsWith('literalDomain@slots.x')), 'explicit epley under the engine default')
})

// ── Z3: the declared inverse honors the declared cap (A-C3, B-W3, C-5) ──────

const loadForApp = (r: number, version = 1): Term => ({ k: 'app', def: { id: 'lib/load-for', version }, args: { e1rm: lit(120, 'kg'), reps: lit(r, 'rep'), rir: lit(0, 'rir') } }) as unknown as Term
const evalWith = (tm: Term, e1rm?: { formula: 'epley' | 'brzycki' | 'lombardi'; maxReps?: number }, r = reg) => EV.evaluate(tm, EV.ctxOf(r, e1rm ? { e1rm } : {})).value

t('', 'Z3 (fail-first, A-p1): the inverse honors maxReps for EVERY formula, Epley included: out-of-cap input is typed absence, never a number the forward read refuses', () => {
  eq(evalWith(loadForApp(12), { formula: 'brzycki', maxReps: 10 }), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'brzycki', reps: 12, cap: 10 } }, 'brzycki over the cap')
  eq(evalWith(loadForApp(12), { formula: 'epley', maxReps: 10 }), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'epley', reps: 12, cap: 10 } }, 'epley over the cap (the special case must not be skipped)')
  const v = evalWith(loadForApp(8), { formula: 'epley', maxReps: 10 })
  near(v.v === 'q' ? v.n : NaN, 120 / (1 + 8 / 30), 'within the cap the Epley inverse still computes')
})

t('', 'Z3 (fail-first, C-p8): Lombardi at effective reps 0 is absent, never Infinity (the forward read’s r ≤ 0 skip, mirrored)', () => {
  eq(evalWith(loadForApp(0), { formula: 'lombardi' }), { v: 'none', cause: { k: 'outsideFormulaDomain', formula: 'lombardi', reps: 0 } }, 'r = 0')
})

t('', 'Z3: the interception keys on lib/load-for@1 EXACTLY — a published @2 runs its own body under any declaration', () => {
  const v2 = { ...P.loadFor.def, ref: { id: 'lib/load-for', version: 2 } } as never as Parameters<typeof CD.publish>[0][number]
  const lreg = CD.publish([...P.PUBLISHED, ...ER.PUBLISHED, v2])
  const viaV2 = evalWith(loadForApp(5, 2), { formula: 'brzycki' }, lreg)
  near(viaV2.v === 'q' ? viaV2.n : NaN, 120 / (1 + 5 / 30), '@2 computes its own (Epley) body, not the declared inverse')
  const viaV1 = evalWith(loadForApp(5, 1), { formula: 'brzycki' }, lreg)
  near(viaV1.v === 'q' ? viaV1.n : NaN, (120 * (37 - 5)) / 36, '@1 stays the seam')
})

// ── Z4 + Z9: the judge’s pooled rules (A-C5, C-6, A-W1) ─────────────────────

// Raw issued-step scaffolding: a target with a reps bar and optionally a
// load bar, logged as [reps, load] rows.
const target = (r: number, load?: number) => ({
  role: 'working',
  metrics: { reps: { k: 'fixed', v: { b: 'exact', v: r } }, ...(load !== undefined ? { load: { k: 'fixed', v: { b: 'exact', v: load } } } : {}) },
  restSec: null,
  tempo: null,
  cluster: null,
})
const srcRaw = (count: object, sets_: object[], rows: ([number, number?] | null)[], success?: JU.EventSource['success']): JU.EventSource => ({
  reg,
  slots: [{ slot: 'x', exercise: { id: 'push-up', label: 'P', logging: 'bodyweight_reps' }, steps: [{ id: 'w', key: 'w', count, sets: sets_, block: null, live: null } as never], intensifier: null, trace: { node: lit(1, 'set'), value: { v: 'q', n: 1, dim: {}, unit: 'set' }, kids: [] } as never }],
  performed: { x: { w: rows.map((row) => (row === null ? { values: {}, stages: null } : { values: { reps: row[0], ...(row[1] !== undefined ? { load: row[1] } : {}) }, stages: null })) } },
  facts: [],
  groupScores: {},
  week: 0,
  primary: () => undefined,
  ...(success ? { success } : {}),
})
const vd = (s: JU.EventSource) => JU.verdictOf(s, 'working', 'floor')
const nSets = (n: number, r: number, load?: number) => Array.from({ length: n }, () => target(r, load))

t('', 'Z4 (fail-first, A-p1/A-p7): atLeastSets counts hit sets among ALL logged sets (extras included) against the plan’s ISSUED ceiling, never logged.length', () => {
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 3, 100), [[0, 100], [0, 100], [0, 100], [0, 100], [0, 100], [3, 100], [3, 100], [3, 100]], { x: { atLeastSets: 3 } })), 'hit', 'three good extras beyond five misses still satisfy atLeastSets 3')
  eq(vd(srcRaw({ k: 'until', max: 5, planned: 5 }, nSets(5, 5), [[5]], { x: { atLeastSets: 5 } })), 'unknown', 'an early stop on an until step is unknown, not hit')
  eq(vd(srcRaw({ k: 'until', max: 5, planned: 5 }, nSets(5, 5), [[5], [5], [5], [5], [2]], { x: { atLeastSets: 5 } })), 'missed', 'the ceiling reached with a miss cannot recover')
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 5), [[5]], { x: { atLeastSets: 5 } })), 'unknown', 'four issuable sets remain: not decided')
})

t('', 'Z4 (fail-first, C-p1): a range count caps at its MAX, so sets 4–5 of a 3–5 range count toward the bar', () => {
  const range = { k: 'range', min: 3, max: 5 }
  eq(vd(srcRaw(range, nSets(3, 5), [[4], [4], [4], [5], [5]], { x: { atLeastSets: 2 } })), 'hit', 'two sets hit the bar, in positions beyond the range min')
  eq(vd(srcRaw(range, nSets(3, 5), [[5], [5], [5]], { x: { atLeastSets: 5 } })), 'unknown', 'needed = min(5, cap 5); two issuable sets remain, so not missed and not yet hit')
  eq(vd(srcRaw(range, nSets(3, 5), [[5], [5], [5], [5], [5]], { x: { atLeastSets: 4 } })), 'hit', 'five logged, four needed')
})

t('', 'Z9 (fail-first, A-p1): a make-up set pays reps into totalReps ONLY when every non-reps bar of the step it extends holds for it', () => {
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 3, 100), [[3, 100], [3, 100], [3, 100], [2, 100], [2, 100]], { x: 'totalReps' })), 'missed', '13 of 15 with all expected logged')
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 3, 100), [[3, 100], [3, 100], [3, 100], [2, 100], [2, 100], [3, 100]], { x: 'totalReps' })), 'hit', 'a qualifying make-up set (at the working load) pays in')
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 3, 100), [[3, 100], [3, 100], [3, 100], [2, 100], [2, 100], [3, 20]], { x: 'totalReps' })), 'missed', 'an unloaded make-up set does not')
  eq(vd(srcRaw({ k: 'n', n: 5 }, nSets(5, 3, 100), [[1, 100], [1, 100], [1, 100], [1, 100], [1, 100], [30, 0]], { x: 'totalReps' })), 'missed', 'an empty-bar 30-rep set cannot rescue 5×3 at 100 kg')
})

// The monotonicity properties (Z4 and Z9, the LAW pinned): a seeded sweep
// over step shapes and logs.
const rank = { missed: 0, unknown: 1, hit: 2 } as const
const rng = (seed: number) => () => {
  seed = (seed * 1664525 + 1013904223) >>> 0
  return seed / 2 ** 32
}

t('', 'Z4 PROPERTY: hit is absorbing under any appended set, and appending a fully-hitting set never worsens the verdict', () => {
  const rand = rng(7)
  for (let i = 0; i < 400; i++) {
    const cap = 1 + Math.floor(rand() * 5)
    const count = rand() < 0.4 ? { k: 'n', n: cap } : rand() < 0.5 ? { k: 'range', min: Math.max(1, cap - 2), max: cap } : { k: 'until', max: cap, planned: cap }
    const bar = 3 + Math.floor(rand() * 3)
    const n = 1 + Math.floor(rand() * 6)
    const logged: [number, number?][] = Array.from({ length: Math.floor(rand() * (cap + 3)) }, () => [Math.floor(rand() * (bar + 2)), 100])
    const succ = { x: { atLeastSets: n } }
    const before = vd(srcRaw(count, nSets(cap, bar, 100), logged, succ))
    const anySet: [number, number?] = [Math.floor(rand() * (bar + 2)), rand() < 0.5 ? 100 : 20]
    const afterAny = vd(srcRaw(count, nSets(cap, bar, 100), [...logged, anySet], succ))
    if (before === 'hit') eq(afterAny, 'hit', `hit absorbing: ${JSON.stringify({ cap, count, bar, n, logged, anySet })}`)
    const afterHit = vd(srcRaw(count, nSets(cap, bar, 100), [...logged, [bar, 100]], succ))
    assert(rank[afterHit] >= rank[before], `a hitting set never worsens: ${before} -> ${afterHit} ${JSON.stringify({ cap, count, bar, n, logged })}`)
  }
})

t('', 'Z9 PROPERTY: totalReps pooling is monotone over make-up sets — a qualifying extra never worsens, a non-qualifying extra changes nothing', () => {
  const rand = rng(11)
  for (let i = 0; i < 400; i++) {
    const n = 2 + Math.floor(rand() * 4)
    const bar = 3 + Math.floor(rand() * 3)
    const logged: [number, number?][] = Array.from({ length: n + Math.floor(rand() * 3) }, () => [Math.floor(rand() * (bar + 2)), 100])
    const succ = { x: 'totalReps' as const }
    const before = vd(srcRaw({ k: 'n', n }, nSets(n, bar, 100), logged, succ))
    const afterQ = vd(srcRaw({ k: 'n', n }, nSets(n, bar, 100), [...logged, [Math.floor(rand() * (bar + 2)), 100]], succ))
    assert(rank[afterQ] >= rank[before], `qualifying extra never worsens: ${before} -> ${afterQ} ${JSON.stringify({ n, bar, logged })}`)
    const afterNQ = vd(srcRaw({ k: 'n', n }, nSets(n, bar, 100), [...logged, [bar + 10, 20]], succ))
    eq(afterNQ, before, `non-qualifying extra changes nothing: ${JSON.stringify({ n, bar, logged })}`)
  }
})

// ── Z5: the dead-config scan sees every consumer (B-C1) ─────────────────────

const PUSHUP = exercise('wger:ball-push-up')
const aggConsumer = program({
  id: 'prog/ufx-agg-consumer',
  version: 1,
  says: 'slot rule consumed ONLY by the aggregate verdict read',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: {},
  muscles: ['chest'],
  slots: () => ({ push: P.fixedWork.bind({ lift: PUSHUP, sets: sets(3), reps: reps(10) }, { muscles: { chest: 1 }, success: 'totalReps' }) }),
  days: { A: [single('push')] },
  rotation: { k: 'weekly', days: ['A'] },
  aggregate: {
    state: { stalled: ty.q('one') },
    writableBy: { stalled: ['session', 'owner'] },
    nouns: { stalled: 'stall count' },
    init: () => ({ stalled: num(0) }),
    on: { session: (c) => c.commit({ stalled: byVerdict(c.ev.verdict(), { hit: num(0), missed: add(c.s.stalled, num(1)), unknown: c.s.stalled }) }) },
  },
})

t('', 'Z5 (fail-first, B-P-A): a slot rule consumed only by the program AGGREGATE’s verdict read is live config, not dead — and the verdict actually flips under it', () => {
  eq(progErrors(aggConsumer.def), [], 'checkProgram is clean')
  const run = TK.start(aggConsumer.def, {}, TK.corpusFacts())
  const x = TK.issue(run, D0)
  const perf = { push: { work: [10, 5, 15].map((r) => ({ values: { reps: r }, stages: null })) } }
  const src: JU.EventSource = { reg, slots: x.issued.slots, performed: perf, facts: [], groupScores: {}, week: 0, primary: () => 'chest', success: { push: 'totalReps' } }
  eq(JU.verdictOf(src, 'working', 'floor'), 'hit', '30 pooled reps clear 3×10 (B-P-A2)')
  const { success: _drop, ...noRule } = src
  eq(JU.verdictOf(noRule as JU.EventSource, 'working', 'floor'), 'missed', 'without the rule, the 5-rep set misses')
})

// Two verdict reads: an OPEN one (which a slot rule can bind) and an
// explicit 'allSets' override. Bound with no slot rule, the override
// overrides nothing (W2a); with one, both reads are live.
const allSetsReader = scheme({
  id: 'lib/ufx-allsets-read',
  version: 1,
  says: 'counts hits and strict misses on {lift}',
  params: { lift: ty.exercise('bodyweight_reps') },
  state: { misses: ty.q('one'), hits: ty.q('one') },
  writableBy: { misses: ['session'], hits: ['session'] },
  init: () => ({ misses: num(0), hits: num(0) }),
  plan: (c) => session({ exercise: c.p.lift, steps: (b) => void b.step('w', sets(3), set({ target: { reps: reps(10) } })) }),
  on: {
    session: (c) =>
      c.commit({
        hits: byVerdict(c.ev.verdict(), { hit: add(c.s.hits, num(1)), missed: c.s.hits, unknown: c.s.hits }),
        misses: byVerdict(c.ev.verdict(undefined, 'floor', 'allSets'), { hit: num(0), missed: add(c.s.misses, num(1)), unknown: c.s.misses }),
      }),
  },
})
const bindAllSets = (success?: 'totalReps') =>
  program({
    id: 'prog/ufx-allsets',
    version: 1,
    says: 'x',
    params: {},
    calendar: { weeks: ['train'], repeat: 'cycle' },
    grids: {},
    muscles: ['chest'],
    slots: () => ({ x: { scheme: { id: 'lib/ufx-allsets-read', version: 1 }, args: { lift: PUSHUP.term }, meta: { muscles: { chest: 1 }, ...(success ? { success } : {}) } } }) as never,
    days: { A: [single('x')] },
    rotation: { k: 'weekly', days: ['A'] },
  }).def

t('', 'Z5 (W2a): a read-level allSets bound with NO slot rule overrides nothing — flagged with the same machinery as the unconsumed slot rule', () => {
  const lreg = CD.publish([...P.PUBLISHED, ...ER.PUBLISHED, allSetsReader])
  assert(progErrors(bindAllSets(), lreg).some((c) => c.startsWith('literalDomain@slots.x.meta.success')), 'dead override')
  eq(progErrors(bindAllSets('totalReps'), lreg), [], 'with a slot rule the override is live')
})

// ── Z6: static atLeastSets never refuses a satisfiable configuration ────────

const defaultedCount = scheme({
  id: 'lib/ufx-defaulted-count',
  version: 1,
  says: '{sets} sets of 5 of {lift}, adding {inc} when at least five sets hit',
  params: { lift: ty.exercise('weight_reps'), sets: ty.q('sets'), inc: ty.q('mass') },
  defaults: { sets: sets(3) },
  state: { load: ty.q('mass') },
  writableBy: { load: ['session', 'owner'] },
  init: () => ({ load: kg(100) }),
  plan: (c) => session({ exercise: c.p.lift, steps: (b) => void b.step('work', c.p.sets, set({ target: { reps: reps(5), load: c.s.load } })) }),
  on: { session: (c) => c.commit({ load: byVerdict(c.ev.verdict(undefined, 'floor', { atLeastSets: 5 }), { hit: add(c.s.load, c.p.inc), missed: c.s.load, unknown: c.s.load }) }) },
})

t('', 'Z6 (fail-first, B-probe3): a DEFAULTED count is not its default for refusal purposes — the scheme checks clean, because a binding may raise it', () => {
  eq(codes(CD.checkScheme(defaultedCount.def, reg)), [], 'the scheme is satisfiable under a legal binding')
  const p = program({
    id: 'prog/ufx-ten-sets',
    version: 1,
    says: 'x',
    params: {},
    calendar: { weeks: ['train'], repeat: 'cycle' },
    grids: { load: kg(2.5) },
    muscles: ['quads'],
    slots: () => ({ squat: defaultedCount.bind({ lift: SQUAT, sets: sets(10), inc: kg(2.5) }, { muscles: { quads: 1 } }) }),
    days: { A: [single('squat')] },
    rotation: { k: 'weekly', days: ['A'] },
  })
  const lreg = CD.publish([...P.PUBLISHED, ...ER.PUBLISHED, defaultedCount])
  eq(progErrors(p.def, lreg), [], 'the binding that raises the count checks clean too')
  eq(CD.maxJudgedSets(defaultedCount.def.plan, { ...defaultedCount.def.defaults, ...p.def.slots['squat']!.args }), 10, 'the helper under the binding')
})

t('', 'Z6: the static cap matches the judge’s (Z4): a range count is satisfiable up to its MAX, and a literal shortfall still refuses', () => {
  const rangePlan = scheme({
    id: 'lib/ufx-range-plan',
    version: 1,
    says: '3 to 5 sets on {lift}',
    params: { lift: ty.exercise('weight_reps') },
    state: { load: ty.q('mass') },
    writableBy: { load: ['session', 'owner'] },
    init: () => ({ load: kg(100) }),
    plan: (c) => session({ exercise: c.p.lift, steps: (b) => void b.step('w', { min: sets(3), max: sets(5) }, set({ target: { reps: reps(5), load: c.s.load } })) }),
    on: { session: (c) => c.commit({ load: byVerdict(c.ev.verdict(undefined, 'floor', { atLeastSets: 5 }), { hit: c.s.load, missed: c.s.load, unknown: c.s.load }) }) },
  })
  eq(codes(CD.checkScheme(rangePlan.def, reg)), [], 'atLeastSets 5 on a 3–5 range is satisfiable (the judge caps at max)')
  eq(CD.maxJudgedSets(rangePlan.def.plan, {}), 5, 'the range counts at its ceiling')
  // A plan whose count is LITERALLY 3 sets, under a read of atLeastSets 5:
  // provably unsatisfiable under every binding, still refused.
  const lit3 = {
    ...defaultedCount.def,
    ref: { id: 'lib/ufx-lit3', version: 1 },
    params: { lift: defaultedCount.def.params['lift']!, inc: defaultedCount.def.params['inc']! },
    defaults: undefined,
    plan: JSON.parse(JSON.stringify(defaultedCount.def.plan).replace('{"k":"param","name":"sets"}', JSON.stringify(lit(3, 'set')))),
  }
  assert(codes(CD.checkScheme(lit3 as never, reg)).some((c) => c.startsWith('literalDomain@on.session')), 'a LITERAL 3-set plan under a read of 5 still refuses')
})

// ── Z7: grids are positive quantity literals, everywhere ────────────────────

t('', 'Z7 (fail-first, A-p5/A-p6/C-p7): zero, negative and computed grid terms are typed refusals, at the program and the slot', () => {
  assert(progErrors({ ...P.linear3x5.def, grids: { load: kg(0).term } } as never).includes('literalDomain@grids.load'), 'kg(0) program grid')
  assert(progErrors({ ...P.linear3x5.def, grids: { load: lb(-5).term } } as never).includes('literalDomain@grids.load'), 'lb(-5) program grid')
  assert(progErrors({ ...P.linear3x5.def, grids: { load: mul(lb(2.5), num(2)).term } } as never).includes('boundNotLiteral@grids.load'), 'a computed program grid')
  const withSlot = (g: Term) => {
    const d = JSON.parse(JSON.stringify(P.mixedUnits.def))
    d.slots.barbell.meta.grids = { load: g }
    return d
  }
  assert(progErrors(withSlot(kg(0).term)).includes('literalDomain@slots.barbell.meta.grids.load'), 'kg(0) slot grid')
  assert(progErrors(withSlot(lb(-5).term)).includes('literalDomain@slots.barbell.meta.grids.load'), 'lb(-5) slot grid')
  assert(progErrors(withSlot(mul(lb(5), num(2)).term)).includes('boundNotLiteral@slots.barbell.meta.grids.load'), 'a computed slot grid (the display:{} hole dies with it)')
})

// ── Z10: override ingestion is strict ───────────────────────────────────────

t('', 'Z10 (fail-first, A-p4): an unknown override key is badOverride (a typo cannot read as "no override"), with a typed value and a separate message', () => {
  const r1 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { lapseAfterDay: 5 } as never)
  assert('code' in r1 && r1.code === 'badOverride' && r1.option === 'lapseAfterDay' && r1.value === 5 && typeof r1.message === 'string', `typo key: ${JSON.stringify(r1)}`)
  const r2 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { adherenceWeeks: { calendarAligned: { weekStart: 'Monday', bogus: 1 } } } as never)
  assert('code' in r2 && r2.code === 'badOverride' && r2.option === 'adherenceWeeks.calendarAligned.bogus', `extra aligned key: ${JSON.stringify(r2)}`)
  const r3 = TI.calendarSpecOf(P.linear3x5.def, [], 'x', D0, D0, { adherenceWeeks: { calendarAligned: null } } as never)
  assert('code' in r3 && r3.code === 'badOverride' && typeof r3.message === 'string' && typeof r3.value !== 'string', `the value is the typed offending value, prose in the message: ${JSON.stringify(r3)}`)
})

// ── Z11: formula prose is never misleading (C-4, C-p10) ─────────────────────

t('', 'Z11 (fail-first, C-p10): a read-level formula is named whenever it differs from the program’s EFFECTIVE formula — explicit Epley under a Brzycki program says Epley', () => {
  const read = (formula?: string) => ({ k: 'event', q: { q: 'e1rm', step: 'top', ...(formula ? { formula } : {}) } }) as unknown as Term
  const brz = DS.cxOf(reg, { effectiveFormula: 'brzycki' })
  eq(DS.d(read('epley'), brz), 'the max estimated from “top” (Epley)', 'explicit epley differs from the effective brzycki: named')
  eq(DS.d(read('brzycki'), brz), 'the max estimated from “top”', 'matching the effective formula adds nothing (such a spelling is refused at check anyway, Z2)')
  eq(DS.d(read(), brz), 'the max estimated from “top”', 'no read-level formula follows the program')
  eq(DS.d(read('brzycki'), DS.cxOf(reg)), 'the max estimated from “top” (Brzycki)', 'under the engine default, brzycki is named as before')
  const pc = DD.programCx({ ...P.linear3x5.def, e1rm: { formula: 'brzycki' } }, DS.cxOf(reg))
  eq(pc.effectiveFormula, 'brzycki', 'programCx threads the effective formula (describeProgram and the differential read through it)')
})

// ── Z12: the untested slot-grid paths (B-W4, B-W8, C-7) ─────────────────────

const S_LB5 = UN.canon(5, 'lb')

t('', 'Z12 (fail-first, B-probe2): live resolution of an open field quantizes against the STAMPED slot grid, in the slot’s unit', () => {
  const T = (e: { term: Term }) => e.term
  const base = PJ.exampleProgram(P.apreTopBackoff.def, { lift: T(exercise('wger:192')), small: T(lb(5)), big: T(lb(10)), backoffs: T(sets(2)), keep: T(pct(90)) })
  const def = { ...base, grids: { load: kg(2.5).term } }
  ;(def.slots['x']!.meta as { grids?: unknown }).grids = { load: lb(5).term }
  const rt0 = PO.runtime(reg, def as never, { id: 'ufx-apre', anchor: D0, activatedOn: D0 })
  const facts = TK.factsOf({ e1rm: { 'wger:192': TK.q(100, 'kg') } })
  const head = ST.activate(rt0, {}, facts)
  const r = ST.prescribe(rt0, ST.ledgerOf(head), 'A', facts, D0)
  assert(!('code' in r.issued), 'issued')
  const issued = r.issued
  eq(issued.stamp.slotGrids, { x: { grids: { load: S_LB5 }, display: { load: 'lb' } } }, 'the stamp carries the slot grid')
  const logged = { x: { top: [{ values: { reps: 6, load: 80 }, stages: null }] } }
  const rows = IS.resolveLive(rt0, issued, logged as never, [])
  const loads = rows.filter((x) => x.metric === 'load' && x.value.k === 'fixed').map((x) => (x.value as { v: { v: number } }).v.v)
  assert(loads.length === 2, 'both backoff sets resolve')
  for (const v of loads) {
    near(v / S_LB5, Math.round(v / S_LB5), 'on the lb grid exactly', 1e-12)
    assert(Math.abs(v / 2.5 - Math.round(v / 2.5)) > 1e-9, 'NOT on the program’s kg grid')
  }
  eq(UN.shown(loads[0]!, 'lb'), 160, 'shows a whole lb number')
})

t('', 'Z12 (fail-first, B-W4): setsDue evaluates under the slot’s stamped display seam (the slotGrids stamp threads through)', () => {
  const cond: Term = { k: 'cmp', op: '==', a: { k: 'round', mode: 'nearest', a: lit(101.25, 'kg'), step: lit(2.5, 'kg') }, b: lit(102.5, 'kg') } as unknown as Term
  const tg = target(5)
  const st = { id: 'w', key: 'w', count: { k: 'while', max: 3, planned: 3 }, sets: [tg, tg, tg], block: null, live: { cond, frame: { vars: {}, reads: {} } } }
  const view = { slot: 'x', exercise: { id: 'push-up', label: 'Push-Up', logging: 'bodyweight_reps' }, steps: [st], intensifier: null, trace: { node: cond, value: { v: 'bool', b: true }, kids: [] } }
  const sg = { x: { grids: { load: S_LB5 }, display: { load: 'lb' as const } } }
  eq(IS.setsDue({ reg }, view as never, st as never, { w: [{ values: { reps: 5 }, stages: null }] }, { ties: 'up', display: {}, slotGrids: sg }), 2, 'the ties-up stamp still decides under a slot grid')
  eq(IS.setsDue({ reg }, view as never, st as never, { w: [{ values: { reps: 5 }, stages: null }] }, { display: {}, slotGrids: sg }), 1, 'and default ties under the same slot grid')
})

t('', 'Z12 (fail-first, B-W8): ties-up composes with a slot grid at the sink — a seed exactly between two lb steps rounds up under ties: up, down otherwise', () => {
  let E: number | null = null
  let tie = 0
  for (let k = 30; k < 60; k++) {
    const cand = (k + 0.5) * S_LB5
    const e = cand * 1.2
    if (e / 1.2 === cand && UN.nearestStep(cand, S_LB5, 'up') !== UN.nearestStep(cand, S_LB5)) {
      E = e
      tie = cand
      break
    }
  }
  assert(E !== null, 'a representable tie exists in range')
  const facts = TK.factsOf({ e1rm: { 'wger:111': TK.q(120, 'kg'), 'wger:192': TK.q(E!, 'kg') } })
  const down = TK.issue(TK.start(P.mixedUnits.def, {}, facts), D0, facts).issued
  const up = TK.issue(TK.start({ ...P.mixedUnits.def, ties: 'up' } as never, {}, facts, 'ufx-ties-up'), D0, facts).issued
  eq(TK.loadOf(down, 'barbell'), UN.nearestStep(tie, S_LB5), 'default ties round the tie down on the slot grid')
  eq(TK.loadOf(up, 'barbell'), UN.nearestStep(tie, S_LB5, 'up'), 'ties: up rounds the same tie up, against the SLOT grid')
  eq(up.stamp.ties, 'up', 'and the stamp records the direction beside the slot grid')
})

t('', 'Z12: the slot-grid program is CORPUS now (prog/mixed-units in the shared registry), and its issued prose is grid-native per slot', () => {
  assert(reg.programs.get('prog/mixed-units@1'), 'published in the shared registry (the differential iterates it)')
  const facts = TK.factsOf({ e1rm: { 'wger:111': TK.q(120, 'kg'), 'wger:192': TK.q(222, 'lb') } })
  const { issued } = TK.issue(TK.start(P.mixedUnits.def, {}, facts), D0, facts)
  const text = DR.sessionText(issued, reg).join('\n')
  assert(text.includes('185 lb'), `the lb slot renders in lb: ${text}`)
  assert(text.includes('100 kg'), 'the kg slot renders in kg, in the same session')
})

done()
