/**
 * units.test.ts — the units addendum (U1–U3, owner-ratified): the pinned
 * kg/lb factor, per-slot grids, and the permanent mixed-unit regression
 * ("just convert, except grids"). Modules are imported as namespaces, as in
 * cfgfix.test.ts, so a test that needs what the frozen pre-round oracle
 * lacks fails alone; the fail-first run against synthesis-cfgfix/ is
 * ../units-prefix.txt (regenerated by ../units-prefix.sh).
 * Run: tsx units.test.ts
 */
import { add, exercise, kg, lb, num, pct, reps, sets, type Term } from './algebra'
import * as CD from './checkdefs'
import * as DS from './describe'
import * as DD from './describe-defs'
import * as DR from './describe-run'
import type { TypeError } from './engine'
import * as P from './programs'
import * as TK from './testkit'
import { program, single } from './structure'
import * as UN from './units'

const { t, done } = TK.suite('units')
const assert: (ok: unknown, msg: string) => asserts ok = TK.assert
const { eq, near, reg, D0 } = TK
const codes = (es: readonly TypeError[]) => es.map((e) => `${e.code}@${e.path.join('.')}`)
const progErrors = (def: Parameters<typeof CD.checkProgram>[0]) => codes(CD.checkProgram(def, reg).flatMap((r) => r.errors))

const SQUAT = exercise('wger:111')
const BENCH = exercise('wger:192')
/** The canonical lb step and the exact initial loads, in the pinned
 *  operation order (one multiply by the factor, binary64, no intermediate
 *  rounding; then the Epley inverse at RIR 1: e ÷ 1.2). */
const STEP_LB5 = 5 * UN.LB_IN_KG
const M0 = 120 / 1.2 // the kg slot's seed: e1rm 120 kg
const B0 = (222 * UN.LB_IN_KG) / 1.2 // the lb slot's seed: e1rm 222 lb → 185 lb

// ── U1: the factor, pinned ──────────────────────────────────────────────────

t('', 'U1: LB_IN_KG is exactly 0.45359237 (the legal definition) and is THE lb scale: every lb↔kg conversion routes through it', () => {
  eq(UN.LB_IN_KG, 0.45359237, 'the named constant')
  eq(UN.UNITS.lb.scale, UN.LB_IN_KG, 'the unit record reads the constant (the audit: no other copy of the factor exists)')
})

t('', 'U1: the conversion is exact at the boundary: 135 lb is the single binary64 product 135 × 0.45359237, and the display round-trips', () => {
  eq(UN.canon(135, 'lb'), 135 * 0.45359237, 'one multiply, no intermediate rounding')
  near(UN.canon(135, 'lb'), 61.23496995, 'the decimal value', 1e-12)
  eq(UN.shown(UN.canon(135, 'lb'), 'lb'), 135, 'canonical ÷ the factor round-trips the authored number')
})

t('', 'U1: mixed-unit arithmetic is one canonical sum (U-L1): 100 kg + 5 lb carries the exact canonical value', () => {
  const v = TK.ev(add(kg(100), lb(5)))
  assert(v.v === 'q', 'a quantity')
  eq(v.n, 100 + 5 * UN.LB_IN_KG, 'canonical values added, exactly')
})

// ── the worked mixed-unit program (U2 + U3) ─────────────────────────────────

/** A kg program grid (machines) and an lb slot grid (barbell), with the
 *  increments CROSSED: an lb increment on the kg grid and a kg increment on
 *  the lb grid. This is the permanent regression for "convert exactly at the
 *  boundary, never convert a grid". */
const mix = program({
  id: 'prog/mixed-units',
  version: 1,
  says: 'Mixed units: a kg default grid with an lb slot grid, increments crossed',
  params: {},
  calendar: { weeks: ['train'], repeat: 'cycle' },
  grids: { load: kg(2.5) },
  muscles: ['quads', 'chest'],
  slots: () => ({
    machine: P.linearGated.bind({ lift: SQUAT, sets: sets(3), reps: reps(5), inc: lb(5), backoff: pct(90), stalls: num(3) }, { muscles: { quads: 1 } }),
    barbell: P.linearGated.bind({ lift: BENCH, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { chest: 1 }, grids: { load: lb(5) } }),
  }),
  days: { A: [single('machine'), single('barbell')] },
  rotation: { k: 'alternate', days: ['A'], perWeek: 2 },
})

const FACTS = TK.factsOf({ e1rm: { 'wger:111': TK.q(120, 'kg'), 'wger:192': TK.q(222, 'lb') } })
const started = () => TK.start(mix.def, {}, FACTS)

t('', 'U2: the program checks clean: a slot grid that DIFFERS from the program grid is legal config, not a refusal', () => {
  eq(progErrors(mix.def), [], 'no refusals')
})

t('', 'U2/U3: the sink lands each slot on ITS grid in the grid’s unit: kg slot on 2.5 kg multiples, lb slot on exact 5 lb multiples (never a converted grid)', () => {
  const { issued } = TK.issue(started(), D0, FACTS)
  near(TK.loadOf(issued, 'machine') ?? NaN, M0, 'the kg slot seeds at 100 kg (120 ÷ 1.2), already on its grid', 1e-12)
  eq(TK.loadOf(issued, 'barbell'), 37 * STEP_LB5, 'the lb slot lands on EXACTLY 37 × (5 × 0.45359237) kg = 185 lb: quantization against the lb grid, in lb')
  eq(UN.shown(TK.loadOf(issued, 'barbell')!, 'lb'), 185, 'and shows a whole lb number')
})

t('', 'U2: the stamp carries the slot grid it issued under (grids canonical, display the declared unit), beside the program grids', () => {
  const { issued } = TK.issue(started(), D0, FACTS)
  eq(issued.stamp.grids, { load: 2.5 }, 'the program grid, canonical kg')
  eq(Object.keys(issued.stamp.slotGrids ?? {}), ['barbell'], 'only the declaring slot is stamped')
  eq(issued.stamp.slotGrids!['barbell'], { grids: { load: 5 * UN.LB_IN_KG }, display: { load: 'lb' } }, 'the resolved slot grid: canonical step and the grid’s own unit')
  eq(issued.stamp.display['load'], 'kg', 'the program display unit is untouched')
})

t('', 'U3: prose is grid-native per slot: the kg slot says kg, the lb slot says lb, in one session', () => {
  const { issued } = TK.issue(started(), D0, FACTS)
  const lines = DR.sessionText(issued, reg)
  assert(lines.some((l) => l.includes('Squat') && l.includes('100 kg')), `the kg slot in kg: ${lines.join(' | ')}`)
  assert(lines.some((l) => l.includes('Bench') && l.includes('185 lb')), `the lb slot in lb: ${lines.join(' | ')}`)
})

t('', 'U3 (U-L3): viewer conversion is display-only with the pinned three-decimal rounding; issued values and grids do not move', () => {
  const { issued } = TK.issue(started(), D0, FACTS)
  const asKg = DR.sessionText(issued, reg, { mass: 'kg' })
  const asLb = DR.sessionText(issued, reg, { mass: 'lb' })
  const bkg = UN.trimNumber(37 * STEP_LB5) // 83.915: String(Number((37 × step).toFixed(3)))
  assert(asKg.some((l) => l.includes('Bench') && l.includes(`${bkg} kg`)), `the lb slot under a kg viewer, display-exact: ${asKg.join(' | ')}`)
  const mlb = UN.trimNumber(UN.shown(M0, 'lb')) // 220.462
  assert(asLb.some((l) => l.includes('Squat') && l.includes(`${mlb} lb`)), `the kg slot under an lb viewer: ${asLb.join(' | ')}`)
  eq(TK.loadOf(issued, 'barbell'), 37 * STEP_LB5, 'the issued fact is untouched: conversion never feeds back (no re-quantization)')
})

t('', 'U3: the crossed increments, both directions: +5 lb sinks onto the kg grid, +2.5 kg sinks onto the lb grid, each in exact canonical math', () => {
  const x1 = TK.issue(started(), D0, FACTS)
  const closed = TK.close(x1.run, x1.issued, TK.asPrescribed(x1.issued), D0)
  assert(!('code' in (closed.result as object)) || (closed.result as { k?: string }).k === 'applied', 'the session landed')
  eq(TK.num(TK.stateOf(closed.run, 'machine', 'load')), M0 + 5 * UN.LB_IN_KG, 'kg state + the exact lb increment (converted at the boundary, once)')
  eq(TK.num(TK.stateOf(closed.run, 'barbell', 'load')), B0 + 2.5, 'lb-seeded state + the exact kg increment (state is canonical and un-sunk)')
  const x2 = TK.issue(closed.run, TK.day('2026-10-07'), FACTS)
  eq(TK.loadOf(x2.issued, 'machine'), 41 * 2.5, '102.26796185 kg on the 2.5 kg grid → 102.5 kg (nearest, ties down)')
  eq(TK.loadOf(x2.issued, 'barbell'), 38 * STEP_LB5, '(185 lb + 2.5 kg) on the 5 lb grid → 190 lb exactly')
  assert(DR.sessionText(x2.issued, reg).some((l) => l.includes('190 lb')), 'and the prose says 190 lb')
})

t('', 'U2: the program description states the slot grid on the slot’s line, in the grid’s unit', () => {
  const lines = DD.describeProgram(mix.def, DS.cxOf(reg))
  assert(lines.some((l) => l.includes('2.5 kg grid')), `the program grid line: ${lines.find((l) => l.includes('grid'))}`)
  assert(lines.some((l) => l.includes('barbell') && l.includes('5 lb grid') && l.includes("this slot's grid")), `the slot line: ${lines.find((l) => l.includes('barbell'))}`)
})

// ── U2: the refusals (the one-form law and the dimension rule) ──────────────

const withBarbellGrids = (grids: unknown): Parameters<typeof CD.checkProgram>[0] => {
  const def = JSON.parse(JSON.stringify(mix.def)) as typeof mix.def
  ;(def.slots['barbell']!.meta as { grids?: unknown }).grids = grids
  return def
}

t('', 'U2 (fail-first): a slot grid spelling the program’s own grid is refused — one form per meaning, through the options table', () => {
  const errs = progErrors(withBarbellGrids({ load: kg(2.5).term }))
  eq(errs, ['literalDomain@slots.barbell.meta.grids.load'], 'the default (the program’s grids) is omission')
})

t('', 'U2 (fail-first): a slot grid off the metric’s dimension is refused (the unitMismatch posture)', () => {
  const errs = progErrors(withBarbellGrids({ load: { k: 'lit', lit: { k: 'q', v: 30, unit: 's' } } as Term }))
  eq(errs, ['unitMismatch@slots.barbell.meta.grids.load'], 'a 30 s load grid is not a mass')
})

t('', 'U2 (fail-first, Y10 posture): malformed slot-grid JSON is a typed refusal at its path, never a crash', () => {
  eq(progErrors(withBarbellGrids({})), ['literalDomain@slots.barbell.meta.grids'], '{} spells the default: omit it')
  eq(progErrors(withBarbellGrids(null)), ['unknownName@slots.barbell.meta.grids'], 'null is not a grids record')
  eq(progErrors(withBarbellGrids({ pace: kg(1).term })), ['unknownName@slots.barbell.meta.grids.pace'], 'only load and distance carry grids')
  eq(progErrors(withBarbellGrids({ load: 5 })), ['unknownName@slots.barbell.meta.grids.load'], 'a bare number is not a term')
})

t('', 'U2: a kg slot grid of the program’s VALUE in another unit is a DIFFERENT grid (the display unit is part of the meaning), and the embedding drops an empty grids record', () => {
  const errs = progErrors(withBarbellGrids({ load: { k: 'lit', lit: { k: 'q', v: 2.5 / UN.LB_IN_KG, unit: 'lb' } } as Term }))
  eq(errs, [], 'a 5.51155… lb grid displays lb: legal, not the default')
  const b = P.linearGated.bind({ lift: BENCH, sets: sets(3), reps: reps(5), inc: kg(2.5), backoff: pct(90), stalls: num(3) }, { muscles: { chest: 1 }, grids: {} })
  eq('grids' in b.meta, false, 'the embedding has ONE spelling of "the program’s grids": omission')
})

done()
